/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.19.16
 *
 *     Copyright: (c) 2018 by Total Control Software
 *     License:   wxWindows License
 */

#include "sipAPI_aui.h"


        #include <wx/aui/framemanager.h>


PyDoc_STRVAR(doc_wxAuiPaneButtonArray_append, "append(self, obj: AuiPaneButton)");

extern "C" {static PyObject *meth_wxAuiPaneButtonArray_append(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_wxAuiPaneButtonArray_append(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = SIP_NULLPTR;

    {
         ::wxAuiPaneButton* obj;
         ::wxAuiPaneButtonArray *sipCpp;

        static const char *sipKwdList[] = {
            sipName_obj,
        };

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, sipKwdList, SIP_NULLPTR, "BJ9", &sipSelf, sipType_wxAuiPaneButtonArray, &sipCpp, sipType_wxAuiPaneButton, &obj))
        {
        sipCpp->Add(*obj);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_AuiPaneButtonArray, sipName_append, doc_wxAuiPaneButtonArray_append);

    return SIP_NULLPTR;
}


PyDoc_STRVAR(doc_wxAuiPaneButtonArray_index, "index(self, obj: AuiPaneButton) -> int");

extern "C" {static PyObject *meth_wxAuiPaneButtonArray_index(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_wxAuiPaneButtonArray_index(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = SIP_NULLPTR;

    {
         ::wxAuiPaneButton* obj;
         ::wxAuiPaneButtonArray *sipCpp;

        static const char *sipKwdList[] = {
            sipName_obj,
        };

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, sipKwdList, SIP_NULLPTR, "BJ9", &sipSelf, sipType_wxAuiPaneButtonArray, &sipCpp, sipType_wxAuiPaneButton, &obj))
        {
            int sipRes = 0;
            sipErrorState sipError = sipErrorNone;

        int idx = sipCpp->Index(*obj, false);
        if (idx == wxNOT_FOUND) {
            sipError = sipErrorFail;
            wxPyErr_SetString(PyExc_ValueError,
                              "sequence.index(x): x not in sequence");
            }
        sipRes = idx;

            if (sipError == sipErrorFail)
                return 0;

            if (sipError == sipErrorNone)
            {
            return SIPLong_FromLong(sipRes);
            }

            sipAddException(sipError, &sipParseErr);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_AuiPaneButtonArray, sipName_index, doc_wxAuiPaneButtonArray_index);

    return SIP_NULLPTR;
}


extern "C" {static int slot_wxAuiPaneButtonArray___contains__(PyObject *,PyObject *);}
static int slot_wxAuiPaneButtonArray___contains__(PyObject *sipSelf,PyObject *sipArg)
{
     ::wxAuiPaneButtonArray *sipCpp = reinterpret_cast< ::wxAuiPaneButtonArray *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_wxAuiPaneButtonArray));

    if (!sipCpp)
        return -1;

    PyObject *sipParseErr = SIP_NULLPTR;

    {
         ::wxAuiPaneButton* obj;

        if (sipParseArgs(&sipParseErr, sipArg, "1J9", sipType_wxAuiPaneButton, &obj))
        {
            int sipRes = 0;

        int idx = sipCpp->Index(*obj, false);
        sipRes = idx != wxNOT_FOUND;

            return sipRes;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_AuiPaneButtonArray, sipName___contains__, SIP_NULLPTR);

    return -1;
}


extern "C" {static PyObject *slot_wxAuiPaneButtonArray___getitem__(PyObject *,PyObject *);}
static PyObject *slot_wxAuiPaneButtonArray___getitem__(PyObject *sipSelf,PyObject *sipArg)
{
     ::wxAuiPaneButtonArray *sipCpp = reinterpret_cast< ::wxAuiPaneButtonArray *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_wxAuiPaneButtonArray));

    if (!sipCpp)
        return SIP_NULLPTR;

    PyObject *sipParseErr = SIP_NULLPTR;

    {
        long index;

        if (sipParseArgs(&sipParseErr, sipArg, "1l", &index))
        {
             ::wxAuiPaneButton*sipRes = 0;
            sipErrorState sipError = sipErrorNone;

            if (0 > index)
                index += sipCpp->GetCount();

            if ((index < sipCpp->GetCount()) && (0 <= index)) {
                sipRes = &sipCpp->Item(index);
            }
            else {
                wxPyErr_SetString(PyExc_IndexError, "sequence index out of range");
                sipError = sipErrorFail;
            }

            if (sipError == sipErrorFail)
                return 0;

            if (sipError == sipErrorNone)
            {
            return sipConvertFromType(sipRes,sipType_wxAuiPaneButton,SIP_NULLPTR);
            }

            sipAddException(sipError, &sipParseErr);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_AuiPaneButtonArray, sipName___getitem__, SIP_NULLPTR);

    return SIP_NULLPTR;
}


extern "C" {static SIP_SSIZE_T slot_wxAuiPaneButtonArray___len__(PyObject *);}
static SIP_SSIZE_T slot_wxAuiPaneButtonArray___len__(PyObject *sipSelf)
{
     ::wxAuiPaneButtonArray *sipCpp = reinterpret_cast< ::wxAuiPaneButtonArray *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_wxAuiPaneButtonArray));

    if (!sipCpp)
        return 0;


    {
        {
            SIP_SSIZE_T sipRes = 0;

        sipRes = sipCpp->GetCount();

            return sipRes;
        }
    }

    return 0;
}


/* Call the instance's destructor. */
extern "C" {static void release_wxAuiPaneButtonArray(void *, int);}
static void release_wxAuiPaneButtonArray(void *sipCppV, int)
{
    Py_BEGIN_ALLOW_THREADS

    delete reinterpret_cast< ::wxAuiPaneButtonArray *>(sipCppV);

    Py_END_ALLOW_THREADS
}


extern "C" {static void assign_wxAuiPaneButtonArray(void *, SIP_SSIZE_T, void *);}
static void assign_wxAuiPaneButtonArray(void *sipDst, SIP_SSIZE_T sipDstIdx, void *sipSrc)
{
    reinterpret_cast< ::wxAuiPaneButtonArray *>(sipDst)[sipDstIdx] = *reinterpret_cast< ::wxAuiPaneButtonArray *>(sipSrc);
}


extern "C" {static void *array_wxAuiPaneButtonArray(SIP_SSIZE_T);}
static void *array_wxAuiPaneButtonArray(SIP_SSIZE_T sipNrElem)
{
    return new  ::wxAuiPaneButtonArray[sipNrElem];
}


extern "C" {static void *copy_wxAuiPaneButtonArray(const void *, SIP_SSIZE_T);}
static void *copy_wxAuiPaneButtonArray(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new  ::wxAuiPaneButtonArray(reinterpret_cast<const  ::wxAuiPaneButtonArray *>(sipSrc)[sipSrcIdx]);
}


extern "C" {static void dealloc_wxAuiPaneButtonArray(sipSimpleWrapper *);}
static void dealloc_wxAuiPaneButtonArray(sipSimpleWrapper *sipSelf)
{
    if (sipIsOwnedByPython(sipSelf))
    {
        release_wxAuiPaneButtonArray(sipGetAddress(sipSelf), 0);
    }
}


extern "C" {static void *init_type_wxAuiPaneButtonArray(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_wxAuiPaneButtonArray(sipSimpleWrapper *, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
     ::wxAuiPaneButtonArray *sipCpp = SIP_NULLPTR;

    {
        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, SIP_NULLPTR, sipUnused, ""))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new  ::wxAuiPaneButtonArray();
            Py_END_ALLOW_THREADS

            return sipCpp;
        }
    }

    {
        const  ::wxAuiPaneButtonArray* a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, SIP_NULLPTR, sipUnused, "J9", sipType_wxAuiPaneButtonArray, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new  ::wxAuiPaneButtonArray(*a0);
            Py_END_ALLOW_THREADS

            return sipCpp;
        }
    }

    return SIP_NULLPTR;
}


/* Define this type's Python slots. */
static sipPySlotDef slots_wxAuiPaneButtonArray[] = {
    {(void *)slot_wxAuiPaneButtonArray___contains__, contains_slot},
    {(void *)slot_wxAuiPaneButtonArray___getitem__, getitem_slot},
    {(void *)slot_wxAuiPaneButtonArray___len__, len_slot},
    {0, (sipPySlotType)0}
};


static PyMethodDef methods_wxAuiPaneButtonArray[] = {
    {SIP_MLNAME_CAST(sipName_append), SIP_MLMETH_CAST(meth_wxAuiPaneButtonArray_append), METH_VARARGS|METH_KEYWORDS, SIP_MLDOC_CAST(doc_wxAuiPaneButtonArray_append)},
    {SIP_MLNAME_CAST(sipName_index), SIP_MLMETH_CAST(meth_wxAuiPaneButtonArray_index), METH_VARARGS|METH_KEYWORDS, SIP_MLDOC_CAST(doc_wxAuiPaneButtonArray_index)}
};

PyDoc_STRVAR(doc_wxAuiPaneButtonArray, "\1AuiPaneButtonArray()\n"
"AuiPaneButtonArray(AuiPaneButtonArray)");


sipClassTypeDef sipTypeDef__aui_wxAuiPaneButtonArray = {
    {
        -1,
        SIP_NULLPTR,
        SIP_NULLPTR,
        SIP_TYPE_CLASS,
        sipNameNr_wxAuiPaneButtonArray,
        {SIP_NULLPTR},
        SIP_NULLPTR
    },
    {
        sipNameNr_AuiPaneButtonArray,
        {0, 0, 1},
        2, methods_wxAuiPaneButtonArray,
        0, SIP_NULLPTR,
        0, SIP_NULLPTR,
        {SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR},
    },
    doc_wxAuiPaneButtonArray,
    -1,
    -1,
    SIP_NULLPTR,
    slots_wxAuiPaneButtonArray,
    init_type_wxAuiPaneButtonArray,
    SIP_NULLPTR,
    SIP_NULLPTR,
#if PY_MAJOR_VERSION >= 3
    SIP_NULLPTR,
    SIP_NULLPTR,
#else
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
#endif
    dealloc_wxAuiPaneButtonArray,
    assign_wxAuiPaneButtonArray,
    array_wxAuiPaneButtonArray,
    copy_wxAuiPaneButtonArray,
    release_wxAuiPaneButtonArray,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR
};
