
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-04T10:51:14+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "dc5bbf00467beeaf2017b7a8242f048f16ed5c40",
 "version": "0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
