
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-31T10:45:42-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "4e6680440af645f9af9529009674d9705497bcd6",
 "version": "0.71.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
