[tool.poetry]
name = "dbvirus-cacher"
version = "0.0.4"
description = ""
authors = ["Felipe Rodrigues <felipe@felipevr.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
pymongo = "^3.9"
mongoengine = "^0.18.2"
pytz = "^2019.3"

[tool.poetry.dev-dependencies]
black = {version = "^18.3-alpha.0", allows-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
