
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-06T10:33:54-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "e643ec7d704dae1f69ecf1c987a1018d78b864bd",
 "version": "0.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
