# This file automatically generated by
#    C:\Jenkins\workspace\python\python-scripted-build-pipeline\couchbase-python-client\couchbase_version.py
# at
#    2019-11-06 05:54:51.375473
__version__ = '2.5.9'