[tool.poetry]
name = "red-connector-ftp"
version = "0.2.0"
authors = ["Christoph Jansen <Christoph.Jansen@htw-berlin.de>", "Bruno Schilling <Bruno.Schilling@student.htw-berlin.de>"]
license = "AGPL-3.0"
readme = "README.md"
repository = "https://github.com/curious-containers/red-connector-ftp"
homepage = "https://www.curious-containers.cc/"
description = "RED Connector FTP is part of the Curious Containers project."

[tool.poetry.dependencies]
python = "^3.4"
jsonschema = "^3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
red-connector-ftp = 'red_connector_ftp.ftp.main:main'
red-connector-ftp-archive = 'red_connector_ftp.ftp_archive.main:main'
