language: python
matrix:
  include:
  - python: '2.7'
    env: PYRO="Pyro"  YAML="pyyaml"
  #- python: '2.7'
  #  env: PYRO="Pyro" JYTHON="org.python:jython-installer:2.7.0"
  - python: '3.4'
    env: PYRO="Pyro4" YAML="pyyaml"
  - python: '3.5'
    env: PYRO="Pyro4" YAML="pyyaml"
  - python: '3.6'
    env: PYRO="Pyro4" YAML="pyyaml"
  - python: '3.7'
    env: PYRO="Pyro4" YAML="pyyaml"
  - python: '3.8'
    env: PYRO="Pyro4" YAML="pyyaml"
  - python: '3.6'
    env: PYRO="Pyro4" YAML=""
  - python: pypy
    env: PYRO="Pyro"  YAML="pyyaml"
  - python: pypy3
    env: PYRO="Pyro4" YAML="pyyaml"
install:
- if [ -n "${JYTHON}" ]; then source install_jython.sh; fi
- if [ -n "${YAML}" ]; then pip install pyyaml; fi
- pip install xlrd
- pip install $PYRO
- pip install coverage
- python setup.py develop
script:
#- cd ..
#- cp pyutilib/.coveragerc .
- test.pyutilib --cat=all --cov
after_success:
- pip install codecov
- codecov
- pip install python-coveralls
- coveralls
- cd $TRAVIS_BUILD_DIR
