[tool.poetry]
name = "snmp-fetch"
version = "0.1.7.1"
description = "An opinionated python SNMPv2 library built for rapid database ingestion."
authors = ["Christopher Aubut <christopher@aubut.me>"]
license = "Unlicense"
readme = "README.rst"
homepage = "https://github.com/higherorderfunctor/snmp-fetch"
repository = "https://pypi.org/project/snmp-fetch/"

build = "build.py"

include = ["src/**/*", "CMakeLists.txt", "lib/pybind11/**/CMakeLists.txt", "lib/pybind11/**/*.cmake", "lib/pybind11/include/**/*.h", "lib/pybind11/**/LICENSE", "lib/pybind11/**/README.*"]
exclude = ["build"]

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.16"
pandas = "^0.25"
attrs = "^19.1"
toolz = "^0.10.0"
jupyterlab = {version = "^1.1", optional = true}
distributed = {version = "^2.6", optional = true}

[tool.poetry.dev-dependencies]
pylint = "^2.3"
isort = "^4.3"
flake8 = "^3.7"
flake8-isort = "^2.7"
flake8-docstrings = "^1.3"
mypy = "^0.720.0"
numpy-stubs = {git = "https://github.com/numpy/numpy-stubs.git"}
bandit = "^1.6"
pytest = "^5.0"
pytest-cov = "^2.7"
hypothesis = "^4.32"
snmpsim = "^0.4.7"

[tool.poetry.extras]
notebooks = ["jupyterlab", "distributed"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
