[tool.poetry]
name = "yacof"
version = "0.0.1"
description = ""
authors = ["fbjorn <kopfabschneider@yandex.ru>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
pydantic = "^1.1"
pyyaml = "^5.1"
"ruamel.yaml" = "^0.16.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
yacof-gen = 'yacof.cli:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
