dist: trusty
group: edge
os:
    - linux
    # travis does not support python on osx yet (https://github.com/travis-ci/travis-ci/issues/4729)
language: python
python:
    - "3.6"
addons:
    chrome: stable
before_install:
    # Base SoS
    - sudo apt-get update
    - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
    - wget https://repo.continuum.io/miniconda/Miniconda3-4.5.11-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a

    - pip install pyyaml psutil tqdm nose selenium
    - pip install fasteners pygments networkx pydot pydotplus
    - pip install entrypoints jupyter coverage codacy-coverage pytest pytest-cov python-coveralls
    - conda install pandas numpy

    # SoS Notebook
    - pip install jedi notebook nbconvert nbformat pyyaml psutil tqdm scipy
    - pip install pygments ipython wand graphviz sos sos-notebook
    - python -m sos_notebook.install

    # Python 2
    - conda create -n ipykernel_py2 python=2 ipykernel
    - source activate ipykernel_py2
    - python -m ipykernel install --user
    #- source deactivate ipykernel_py2
    - conda deactivate

    # selenium
    - wget https://chromedriver.storage.googleapis.com/76.0.3809.126/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip -d $HOME/miniconda/bin

sudo: required
install: "pip install . -U"
before_script:
    - cd test
script:
    - pytest -x -v --cov-report=xml

after_success:
    - coverage combine
    - coveralls

notifications:
    email:
        recipients:
            - ben.bob@gmail.com
        on_success: never
        on_failure: always

