from setuptools import setup

setup (
        name="thonny-pydiderot-plugin",
        version="0.0.3",
        description="Un plugin qui configure thonny pour le lycée Diderot à Marseille",
        long_description=open('README.md').read(),
        url="https://github.com/cspaier/thonny-pydiderot-plugin",
        author="Clément Spaier",
        author_email="clement.spaier@gmail.com",
        license="MIT",
        classifiers=[
          "Environment :: MacOS X",
          "Environment :: Win32 (MS Windows)",
          "Environment :: X11 Applications",
          "Intended Audience :: Developers",
          "Intended Audience :: Education",
          "Intended Audience :: End Users/Desktop",
          "License :: OSI Approved :: MIT License",
          "Natural Language :: English",
          "Operating System :: MacOS",
          "Operating System :: Microsoft :: Windows",
          "Operating System :: POSIX",
          "Operating System :: POSIX :: Linux",
          "Programming Language :: Python",
          "Programming Language :: Python :: 3",
          "Programming Language :: Python :: 3 :: Only",
          "Programming Language :: Python :: 3.5",
          "Programming Language :: Python :: 3.6",
          "Programming Language :: Python :: 3.7",
          "Topic :: Education",
          "Topic :: Software Development",
          "Topic :: Software Development :: Embedded Systems",
        ],
        keywords="IDE education programming  Thonny",
        platforms=["Windows", "macOS", "Linux"],
        python_requires=">=3.5",
        install_requires=["thonny >= 3.0.0"],
        include_package_data=True,
        packages=["thonnycontrib.thonny-pydiderot-plugin"],
)
