# coding: utf-8

"""
    SPMO Service

    The Software Project Management Ontology (SPMO) is defined as a layer over the Software Process Ontology, addressing aspects related to scope, time & duration, and cost estimation of intended processes, as well as aspects related to tracking planned versus performed processes.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import spmo_client
from spmo_client.api.project_processes_api import ProjectProcessesApi  # noqa: E501
from spmo_client.rest import ApiException


class TestProjectProcessesApi(unittest.TestCase):
    """ProjectProcessesApi unit test stubs"""

    def setUp(self):
        self.api = spmo_client.api.project_processes_api.ProjectProcessesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_project_processes_create(self):
        """Test case for project_processes_create

        """
        pass

    def test_project_processes_delete(self):
        """Test case for project_processes_delete

        """
        pass

    def test_project_processes_list(self):
        """Test case for project_processes_list

        """
        pass

    def test_project_processes_partial_update(self):
        """Test case for project_processes_partial_update

        """
        pass

    def test_project_processes_read(self):
        """Test case for project_processes_read

        """
        pass

    def test_project_processes_update(self):
        """Test case for project_processes_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
