# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-10 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to=b'mail-queue/attachments')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=250, verbose_name='Message-ID')),
                ('subject', models.CharField(blank=True, max_length=250, verbose_name='Subject')),
                ('to_address', models.EmailField(max_length=250, verbose_name='To')),
                ('bcc_address', models.EmailField(blank=True, max_length=250, verbose_name='BCC')),
                ('from_address', models.EmailField(max_length=250, verbose_name='From')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('html_content', models.TextField(blank=True, verbose_name='HTML Content')),
                ('app', models.CharField(blank=True, max_length=250, verbose_name='App')),
                ('sent', models.DateTimeField(auto_now_add=True, verbose_name='Sent')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=250, verbose_name='Subject')),
                ('to_address', models.EmailField(max_length=250, verbose_name='To')),
                ('bcc_address', models.EmailField(blank=True, max_length=250, verbose_name='BCC')),
                ('from_address', models.EmailField(max_length=250, verbose_name='From')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('html_content', models.TextField(blank=True, verbose_name='HTML Content')),
                ('app', models.CharField(blank=True, max_length=250, verbose_name='App')),
                ('deferred', models.BooleanField(default=False, verbose_name='Deferred')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_attempt', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Last attempt')),
            ],
            options={
                'verbose_name': 'Queue',
                'verbose_name_plural': 'Queues',
            },
        ),
        migrations.AddField(
            model_name='attachment',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_queue_mailer.Queue'),
        ),
    ]
