# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-10-31 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_queue_mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='reply_to',
            field=models.EmailField(blank=True, max_length=250, verbose_name='Reply To'),
        ),
        migrations.AddField(
            model_name='queue',
            name='reply_to',
            field=models.EmailField(blank=True, max_length=250, verbose_name='Reply To'),
        ),
    ]
