# Generated by Django 2.2 on 2019-04-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0005_auto_20190402_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity_relation_type',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entity_type',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='term_relation_type',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trait_type',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
