- name: Generate image name
  set_fact:
    image_name: ipa-{{ image_distro }}-{{ ipa_branch_path }}

- name: Build a DIB image
  command: |
    ironic-python-agent-builder -o {{ image_name }} -b HEAD -v
        {{ "-r {}".format(image_release) if image_release else '' }}
        {{ "--extra-args '{}'".format(dib_extra_args) if dib_extra_args else '' }}
        {{ image_distro }}
  environment:
    # Increase from the default value of 30
    DIB_DHCP_TIMEOUT: 60
    # Use repositories checked out by Zuul (combined with -b HEAD above)
    DIB_REPOLOCATION_ironic_python_agent: '{{ ipa_source_path }}'
    DIB_REPOLOCATION_requirements: '{{ requirements_path }}'

- name: Move the resulting files
  shell: |
    tar -czf "{{ ipa_tar_dir }}/{{ image_name }}.tar.gz" {{ image_name }}*
    mv {{ image_name }}* "{{ ipa_raw_dir }}"
