[tool.poetry]
name = "red-connector-ssh"
version = "1.2"
authors = ["Christoph Jansen <Christoph.Jansen@htw-berlin.de>", "Bruno Schilling <Bruno.Schilling@student.htw-berlin.de>"]
license = "AGPL-3.0"
readme = "README.md"
repository = "https://github.com/curious-containers/red-connector-ssh"
homepage = "https://www.curious-containers.cc/"
description = "RED Connector SSH is part of the Curious Containers project."

[tool.poetry.dependencies]
python = "^3.4"
paramiko = "^2.5"
scp = "^0.13.0"
jsonschema = "^3.0"
pexpect = "^4.7.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
red-connector-ssh = 'red_connector_ssh.main:main'
red-convert-ssh-key = 'red_connector_ssh.convert_ssh_key.main:main'
