
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-15T14:30:49+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "1e0046ec8f1059743a0c837bfb76311007e38036",
 "version": "0.4.0-alpha.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
