# coding: utf-8

"""
    SPMO Service

    The Software Project Management Ontology (SPMO) is defined as a layer over the Software Process Ontology, addressing aspects related to scope, time & duration, and cost estimation of intended processes, as well as aspects related to tracking planned versus performed processes.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import spmo_client
from spmo_client.api.software_project_api import SoftwareProjectApi  # noqa: E501
from spmo_client.rest import ApiException


class TestSoftwareProjectApi(unittest.TestCase):
    """SoftwareProjectApi unit test stubs"""

    def setUp(self):
        self.api = spmo_client.api.software_project_api.SoftwareProjectApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_software_project_uuid_read(self):
        """Test case for software_project_uuid_read

        """
        pass

    def test_software_project_uuid_read_0(self):
        """Test case for software_project_uuid_read_0

        """
        pass


if __name__ == '__main__':
    unittest.main()
