[relay]
syncInterval = 300
updateNetworksInterval = 120
eventQueryTimeout = 20
enableEtherFaucet = false
enableRelayMetaTransaction = false
enableDeployIdentity = false

[relay.rpc]
host = "localhost"
port = 8545
ssl = false

[relay.gasPriceComputation]
method = "rpc"
gasPrice = 0

# Configure logging
[logging.root]
level = "INFO"

[logging.loggers."api.resources"]
level = "DEBUG"

[logging.loggers.node]
level = "DEBUG"
