from zalopaysupport.upload_image import prepareImageResourceBeforeUpload, uploadImagesToZPSVN
from zalopaysupport.rename import renameAllFolderAndFile, renameToRemoveResolutionSuffix
from zalopaysupport.common import yes_no, choose_environment, choose_multi_environment
