
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-05T16:14:16-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "d2ed9f3c27299eada78c7d1a7f0ff50c6c68157c",
 "version": "1.3.4rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
