language: python

os:
  - linux

python:
  - 2.7

addons:
  apt:
    packages:
      - python-setuptools

install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools_scm

script:
  echo "no tests"

deploy:
  provider: pypi
  user: pivarski
  password:
    secure: "yjFNytZi1f++Ap6o3kx8/rwIkXUa1wyR6xA2MxsSa2al15v+NNQwsdXHOAeOz+eFp0HRgzFhLVitF6i+WFWlAojNuNF221j+6Yttd6mBpQQtRAcpCzRrWxgB6PWhbrSs0mA2g7BhZLvbgTFqhRoliuEesf28afwBxCO0CfOcbkXkpQz3IUtn6buNzHvYjEhL5BAt0AS5l8GvBeWyOi05Vlev4AJHpK032C6cMuKdkB7zJLiNcwaZwMKTZQUPwtm7i1oJ9E9tyFx3rM0bzlb8mhzQD/578OziVc5dQg4UxEhbQKijmlSSSvk2jUmGGBlLPnEmMsZmxiqG5JQL74Lx4VLAvk5zjXori8QZmpuNMzL4LDI6W/3+wX0q5Xd5/SsLtMA5aJcp5CEZe0t0tsxiFlLGR3ddJ6B7r2Qb5fSZKvBAr8PNyakoxgFFZcxKfEwHu5Jom/OImYvxMXaPTkROMpT8jmX9QfEyWLFOaqdroFRJvYc3ENBgRSqNFkiKLUMB14kDuNlQbeqN123Sj9UxyDVbxzi5gCIpjJZhG87dqyqLK1QPWkI/50wQpOzm/EXABu37Pavdpdq2ZBydwoLCJfRp6vi8uSWdPGXFLLnTNHPuETOyU2fBXb1wEpgq/ylRB0bgw1O1NZaosR0xM6NvTspy9/AZiOZHlb+0p6ylwFk="
  on:
    tags: true
    branch: master
