
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-07T19:34:49-0600",
 "dirty": true,
 "error": null,
 "full-revisionid": "9d6fe2a311efa59b02fc83dbc6949cc1df8ca906",
 "version": "0+untagged.607.g9d6fe2a.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
