language: python

jobs:
  include:
    - python: "3.7"
    - python: "3.8"
    - python: "3.7-dev"
    - python: "3.8-dev"
    - python: "nightly"
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11
      language: shell
    - name: "Python 3.7.4 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.4
        - choco install codecov
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      after_success:
        - codecov -f coverage.xml
    - stage: deploy
      script: skip
      python: 3.7
      deploy:
        provider: pypi
        user: "__token__"
        password:
          secure: ucKIfGZwGiFYNOzzWJrz783SEjYecsVbKdSGs9XUDucY5nW3D0LTxf4YxZ8WiWbb3fCuWZH4dU9EHELLxEfDz4BlwVPAFbuyfnEOvVcyset2ruI8Xv6cir/AAfNpr84nNwly7N2MRkCXFS+lL4rUnC8Ge4XMBAK0ENP7TpLUSM4uTM3oLROfTdw0Y2IeTnXVjJQtzyXNFZaqrPUozLGMcPfzC7mFimejmJ9R2ZBXjphQ4OLTx2VWm5iKfjJSGbljFAsv+TmKU35vSLYKsh7Tar3bXWpo4AT0JNNt//jQudC7y+zgovGnbrjHkSU5aqS0Ad4gLrrV2Yc6VrKtq7Lg7Hhr765D2LzCsb8kexgx7FkYbPi8YYC7Bfy9m8Q90us5nG0q0ovtcGJHrs1p4LtpwUgzMhEim60lC1IL7Ql0q2qrffmfPQdiZHBIbgsmXS0XVfwdX0xLl44sI9KD5hph6wtpzUasDvWFBaAJ6XA/ult/FxKIdQ4vzjual1Hco5ZOE+2OKxnHRtKZcffFSs29+b7AHENOBWIPchmCU74EqHY76DizibDaAWGw3NqrvZOYVSiOhAgkVKVDVp/lVZDNu4buDiyELIWZrMMupvvAi0U+yDwtkp4CexSCsJbd6+f8twQVve2yKbDg2ZKBpL5dQ2LnkGQTZRyGwnaGO0BfwCo=
        on:
          tags: true
        skip_existing: true

  allow_failures:
    - python: "nightly"

install:
  - pip3 install pipenv
  - pipenv install --dev

script:
  - pipenv run test

after_success:
  - bash <(curl -s https://codecov.io/bash)

