
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-15T14:05:44+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "106928b9423573c961b16643967cf4d4cc7eb448",
 "version": "5.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
