
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-05T16:31:29-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "0222f641acacf522d7fa24053cbd6ac7504b51cb",
 "version": "0.4.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
