
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "1cfa75f522ddebceb54c2ff4a21ef021732f1034",
 "version": "0.6.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
