
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-11T22:27:56+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "fca5d6fcdaee4f1dd34b173750e078abe4372364",
 "version": "0.3.1.post.dev11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
