# coding: utf-8

"""
    Bedrock

    API documentation for Bedrock platform  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class BaseSchemaWithIds(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict):       The key is attribute name
                                  and the value is attribute type.
      attribute_map (dict):       The key is attribute name
                                  and the value is json key in definition.
      readonly_attributes (dict): Set of readonly attributes (will not be
                                  serialised in request body).
    """
    openapi_types = {
        'entity_id': 'str',
        'public_id': 'str'
    }

    attribute_map = {
        'entity_id': 'entity_id',
        'public_id': 'public_id'
    }

    readonly_attributes = {
        'entity_id',
        'public_id'
    }

    def __init__(self, entity_id=None, public_id=None):  # noqa: E501
        """BaseSchemaWithIds - a model defined in OpenAPI"""  # noqa: E501

        self._entity_id = None
        self._public_id = None
        self.discriminator = None


    @classmethod
    def from_response(cls, entity_id=None, public_id=None):  # noqa: E501
        """Instantiate BaseSchemaWithIds from response"""  # noqa: E501
        self = cls.__new__(cls)

        self._entity_id = None
        self._public_id = None
        self.discriminator = None

        if entity_id is not None:
            self.entity_id = entity_id
        if public_id is not None:
            self.public_id = public_id
        return self

    @property
    def entity_id(self):
        """Gets the entity_id of this BaseSchemaWithIds.  # noqa: E501


        :return: The entity_id of this BaseSchemaWithIds.  # noqa: E501
        :rtype: str
        """
        return self._entity_id

    @entity_id.setter
    def entity_id(self, entity_id):
        """Sets the entity_id of this BaseSchemaWithIds.


        :param entity_id: The entity_id of this BaseSchemaWithIds.  # noqa: E501
        :type: str
        """

        self._entity_id = entity_id

    @property
    def public_id(self):
        """Gets the public_id of this BaseSchemaWithIds.  # noqa: E501


        :return: The public_id of this BaseSchemaWithIds.  # noqa: E501
        :rtype: str
        """
        return self._public_id

    @public_id.setter
    def public_id(self, public_id):
        """Sets the public_id of this BaseSchemaWithIds.


        :param public_id: The public_id of this BaseSchemaWithIds.  # noqa: E501
        :type: str
        """

        self._public_id = public_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BaseSchemaWithIds):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
