language: python

dist: xenial

matrix:
    include:
        - &docs
          env: BUILD_DOCS=true
          python: '3.6'
          install:
              - source $TRAVIS_BUILD_DIR/.travis/install_miniconda.sh
              - source $TRAVIS_BUILD_DIR/.travis/create_conda_env.sh
              - python setup.py develop
          script: source $TRAVIS_BUILD_DIR/.travis/build_doc.sh
        - &python36
          python: '3.6'
          env: ORANGE="release"
        - &python37
          python: '3.7'
          env: ORANGE="release"
        - &master
          python: '3.6'
          env: ORANGE="master"

env:
    global:
        - BOTO_CONFIG=/dev/null  # it solves boto travis issue https://github.com/boto/boto/issues/3717

cache:
    apt: true   # does not work for public repos
    directories:
        - $HOME/.cache/pip
        - $HOME/.ccache
        - $HOME/nltk_data
        - $TRAVIS_BUILD_DIR/pyqt

before_cache:   # prevent logs from caching
    - rm -f $HOME/.cache/pip/log/debug.log

before_install:
    - source $TRAVIS_BUILD_DIR/.travis/util.sh
    - pip install -U setuptools pip wheel
    - pip install codecov
    # Orange/openTSNE requires numpy>=1.16.* but cannot update it itself?
    - pip install numpy==1.16.*
    - mkdir -p /home/travis/.local/share/Orange  # create orange app dir

install:
    - source $TRAVIS_BUILD_DIR/.travis/install_orange.sh
    - travis_wait pip install -r requirements.txt
    - pip install sip pyqt5==5.11.*
    - python setup.py develop   # assure version.py is present; required for imports

script:
    - XVFBARGS="-screen 0 1280x1024x24"
    - catchsegv xvfb-run -a -s "$XVFBARGS" coverage run setup.py test

after_success:
    - codecov
