
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-12T07:45:45+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ad62f6a028bdff2edf3dc489ba6a9bbf7fb5f774",
 "version": "0.3.1.post.dev12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
