# Generated by Django 2.1.7 on 2019-04-02 19:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0004_auto_20190305_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='details_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity_relation',
            name='details_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
