# Generated by Django 2.2.6 on 2019-10-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ambition_ae", "0040_auto_20191017_0107")]

    operations = [
        migrations.AlterField(
            model_name="aeinitial",
            name="sae_reason_old",
            field=models.CharField(
                default="QUESTION_RETIRED",
                help_text="If subject deceased, submit a Death Report",
                max_length=50,
                verbose_name='If "Yes", reason for SAE:',
            ),
        ),
        migrations.AlterField(
            model_name="historicalaeinitial",
            name="sae_reason_old",
            field=models.CharField(
                default="QUESTION_RETIRED",
                help_text="If subject deceased, submit a Death Report",
                max_length=50,
                verbose_name='If "Yes", reason for SAE:',
            ),
        ),
        migrations.AddIndex(
            model_name="deathreport",
            index=models.Index(
                fields=["subject_identifier", "action_identifier", "site", "id"],
                name="ambition_ae_subject_ec758c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deathreporttmg",
            index=models.Index(
                fields=["subject_identifier", "action_identifier", "site", "id"],
                name="ambition_ae_subject_809724_idx",
            ),
        ),
        migrations.AlterModelTable(name="deathreport", table=None),
        migrations.AlterModelTable(name="deathreporttmg", table=None),
    ]
