
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "5f618c510f75750afe25794d9837220eddb93862",
 "version": "1.0.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
