
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-30T14:09:03-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "6ae8671e522497ee6ca8befe7408e81fbc69928c",
 "version": "1.41.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
