[tool.poetry]
name = "quantrocket-utils"
version = "0.2.0"
description = "Utility methods for common tasks in QuantRocket."
authors = ["Tim Wedde <timwedde@icloud.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/boosting-alpha-bv/quantrocket-utils"
homepage = "https://github.com/boosting-alpha-bv/quantrocket-utils"

[tool.poetry.dependencies]
python = "^3.6"
arrow = "^0.15.2"
colorama = "^0.4.1"
trading-calendars = "^1.11"
ib-trading-calendars = "^0.1.2"
termcolor = "^1.1"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
pytest = "^5.1"
codecov = "^2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
