repos:
- repo: https://github.com/ambv/black
  rev: 19.3b0
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-ast
  - id: mixed-line-ending
    args: ["--fix=lf"]
  - id: debug-statements
  - id: flake8
    additional_dependencies: [flake8-bugbear, flake8-mypy]
- repo: https://github.com/asottile/pyupgrade
  rev: v1.17.1
  hooks:
  - id: pyupgrade
