
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-08T10:51:28+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9067dd2580fbe1efb885180a2f111490606f315f",
 "version": "0.3.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
