baseUrl: http://example.com
languageCode: en-US
title: example
theme: basic
defaultLanguage: en

languages:
  ru:
    static: static/ru/
    #target: ru/
    #static_target: ru/static2/
    content: content/rus/
  en:
    static: static/en/
    #target: en/
    content: content/en/