
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-04T17:24:21+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "49b0e0c1d312c716640deb8261e0e47950cd5412",
 "version": "0.9.8.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
