# CI for wxPython Phoenix on Azure DevOps

#pipelines:
#- pipeline:
#  

name: CI.$(Date:yyyyMMdd).$(Rev:.r)

trigger:
- master
- wxPy-4.0.x

pr:
  autoCancel: true
  branches:
    include:
    - master
    - wxPy-4.0.x

jobs:
- template: .azure/ci-linux-job.yml
- template: .azure/ci-macos-job.yml
- template: .azure/ci-windows-job.yml



