
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-12T11:36:32-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "659a89c80b19dab08c4262e8f667b55c77f9f1d0",
 "version": "0.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
