"""All Supported Task Pools."""
from .aio_fixed_task_pool_simple import AioFixedTaskPoolSimple
from .aio_fixed_task_pool_lifo import AioFixedTaskPoolLifo
from .aio_fixed_task_pool_priority import AioFixedTaskPoolPriority
from .aio_autoscale_task_pool_simple import AioAutoScaleTaskPoolSimple
from .aio_autoscale_task_pool_lifo import AioAutoScaleTaskPoolLifo
from .aio_autoscale_task_pool_priority import AioAutoScaleTaskPoolPriority
