[tool.poetry]
name = "gaphor"
version = "1.1.1"
description = "Gaphor is the simple modeling tool written in Python."
authors = [
    "Arjan J. Molenaar <gaphor@gmail.com>",
    "Dan Yeaw <dan@yeaw.me>"
]

readme = "README.md"

homepage = "https://gaphor.readthedocs.io/"
repository = "https://github.com/gaphor/gaphor"
documentation = "https://gaphor.readthedocs.io/"

keywords = ["gtk+", "diagram", "UML", "MBSE", "gaphor", "modeling"]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: X11 Applications :: GTK",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Information Technology",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Operating System :: Unix",
    "Programming Language :: Python",
    "Topic :: Multimedia :: Graphics :: Editors :: Vector-Based",
    "Topic :: Software Development :: Documentation",
]

[tool.poetry.dependencies]
python = "^3.7"
pycairo = "^1.18"
PyGObject = "^3.30"
gaphas = "^1.0.0"
importlib_metadata = "^0.23"

[tool.poetry.dev-dependencies]
tomlkit = "^0.5"
pytest = "^5.0"
pytest-cov = "^2.5"
pytest-runner = "^4.2"
black = { version = "^19.3b0", python = "^3.6" }
mypy = "0.730"
pre-commit = "^1.12"
pyinstaller = "^3.5"
sphinx = "^2.2"
recommonmark = "^0.6.0"
sphinx-rtd-theme = "^0.4.3"

[tool.poetry.scripts]
gaphor = 'gaphor:main'
gaphorconvert = 'gaphor.tools.gaphorconvert:main'

[tool.poetry.plugins."gaphor.services"]
"component_registry" = "gaphor.services.componentregistry:ComponentRegistry"
"event_manager" = "gaphor.services.eventmanager:EventManager"
"properties" = "gaphor.services.properties:Properties"
"undo_manager" = "gaphor.services.undomanager:UndoManager"
"element_factory" = "gaphor.UML.elementfactory:ElementFactory"
"file_manager" = "gaphor.ui.filemanager:FileManager"
"recent_files" = "gaphor.ui.recentfiles:RecentFiles"
"main_window" = "gaphor.ui.mainwindow:MainWindow"
"preferences" = "gaphor.ui.preferences:Preferences"
"export_menu" = "gaphor.ui.menufragment:MenuFragment"
"tools_menu" = "gaphor.ui.menufragment:MenuFragment"
"copy" = "gaphor.services.copyservice:CopyService"
"sanitizer" = "gaphor.services.sanitizerservice:SanitizerService"
"help" = "gaphor.services.helpservice:HelpService"
"namespace" = "gaphor.ui.namespace:Namespace"
"toolbox" = "gaphor.ui.toolbox:Toolbox"
"diagrams" = "gaphor.ui.mainwindow:Diagrams"
"consolewindow" = "gaphor.plugins.console:ConsoleWindow"
"elementeditor" = "gaphor.ui.elementeditor:ElementEditor"
"diagram_export" = "gaphor.plugins.diagramexport:DiagramExport"
"xmi_export" = "gaphor.plugins.xmiexport:XMIExport"

[build-system]
requires = ["poetry==1.0.0b3"]
build-backend = "poetry.masonry.api"
