
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-02T18:51:32+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "71e782d26492ddf839b84678dcc91ceef1803fc0",
 "version": "0.11.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
