[tool.poetry]
name = "XRD-Viewer"
version = "1.0.0"
description = "Simple analysis tool for NeXus data files"
authors = ["Sebastian Schenk <sebastian.schenk@physik.uni-halle.de>"]
readme = "README.md"
homepage = "https://gitlab.com/merrx/xrd-viewer"
keywords = ["analysis","diffraction"]
include = ["xrd_viewer/assets/*"]

[tool.poetry.dependencies]
python = "^3.6"
PyQt5 = "^5.0"
matplotlib = "^3.0"
h5py = "^2.9"
numpy = "^1.15"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[tool.poetry.scripts]
xrd-viewer = 'xrd_viewer.__main__:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
