[tool.poetry]
name = "preacher"
version = "0.11.5"
description = "A web API verification tool."
authors = ["Yu Mochizuki <ymoch.dev@gmail.com>"]
readme = "README.md"
homepage = "https://preacher.readthedocs.io/"
repository = "https://github.com/ymoch/preacher"
license = "MIT"
classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Console",
  "Topic :: Software Development :: Testing",
  "Topic :: System :: Monitoring"
]

[tool.poetry.scripts]
preacher-cli = "preacher.app.cli.main:main"

[tool.poetry.dependencies]
python = "^3.7"
aniso8601 = "^8.0"
pyhamcrest = "^1.9"
pyjq = "^2.3"
requests = "^2.21"
"ruamel.yaml" = "^0.15.89"
lxml = "^4.4"
jinja2 = "^2.10"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-runner = "^4.4"
pytest-flakes = "^4.0"
pytest-pycodestyle = "^1.4"
pytest-mypy = "^0.3.2"
pytest-cov = "^2.6"
pytest-xdist = "^1.29"
responder = "^2.0"
sphinx = "^2.2"
sphinx-autobuild = "^0.7.1"
toml = "^0.10.0"
sphinx-intl = "^2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
