[tool.poetry]
name = "dbvirus-searcher"
version = "0.1.1"
description = "SRA data searcher w/ local caching for the DBVirus project"
authors = ["Felipe Rodrigues <felipe@felipevr.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
biopython = "^1.74"
xmltodict = "^0.12"
fire = "^0.2.1"
pytz = "^2019.2"
tqdm = "^4.36"
dbvirus-cacher = "^0.0.2"

[tool.poetry.dev-dependencies]
pylint = "^2.3"
black = {version = "^18.3-alpha.0",allows-prereleases = true}
pytest = "^5.0"
pytest-mock = "^1.10"
jsonschema = "^3.0"
ipython = "^7.7"

[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

