
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-08T10:40:31-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "607811e7cf7f69b0e5571cf96e7e55c4a999d62d",
 "version": "1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
