
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-10T19:29:32+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "711f67868c1cd9b90cc998e5b4cf7ce7eace35e9",
 "version": "0.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
