# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-09 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bee_django_track', '0005_auto_20181031_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertrackrecord',
            options={'ordering': ['-created_at'], 'permissions': (('add_track_other', '\u53ef\u4ee5\u6dfb\u52a0\u5176\u4ed6\u7c7b\u8db3\u8ff9'), ('view_track_other', '\u53ef\u4ee5\u67e5\u770b\u5176\u4ed6\u7c7b\u8db3\u8ff9'))},
        ),
    ]
