# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-18 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee_django_track', '0006_auto_20181109_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertrackrecord',
            name='content_id',
            field=models.IntegerField(null=True),
        ),
    ]
