[tool.poetry]
name = "siva-poetry"
version = "2.0.1"
description = "Simple project"
authors = ["siva <sivakon@outlook.com>"]
packages = [
    { include = "siva_poetry", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.7"
pendulum = "^2.0"
pyyaml = "^5.1"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[tool.poetry.scripts]
# You can directly call the symbol `get_time` because it is exported using __init__.py.
start_pendulum = "siva_poetry:get_time"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
