
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-15T15:00:44+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0758a1e236f8d30c47e4443eddb2ace6ffadda50",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
