[tool.poetry]
name = "geolibs-glutemulo"
packages = [
    { include='glutemulo' }
]
version = "0.1.3"
description = "GeoLibs data ingestor"
authors = ["Geographica <hello@geographica.com>"]
license = "MIT"
readme = "Readme.md"

[tool.poetry.dependencies]
python = "^3.6"
kafka-python = "^1.4"
environs = "^4.1"
fastavro = "^0.21.23"
carto = {version = "^1.4",optional = true}
psycopg2-binary = {version = "^2.8",optional = true}
redis = {version = "^3.2",optional = true}
google-cloud-bigquery = "^1.21"

[tool.poetry.dev-dependencies]
flask = "^1.0"
pytest = "^4.4"
pytest-mock = "^1.10"

[tool.poetry.extras]
carto = ["carto"]
postgres = ["psycopg2-binary"]
redis = ["redis"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
