
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-07T18:25:36-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9faddfa4c36df38447a84d0d28c294d6694b77f8",
 "version": "0.0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
