
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-13T14:02:43+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e68fdb69afd2fa60080ce2aab06fb5870e7837da",
 "version": "0.2.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
