# Generated by Django 2.2.4 on 2019-10-21 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0016_auto_20190327_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSDProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='updated at')),
                ('is_public', models.BooleanField(default=False)),
                ('dsd_id', models.CharField(blank=True, max_length=255, null=True)),
                ('dsd_options', models.TextField(blank=True, null=True)),
                ('productCode', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('EAN1', models.TextField(blank=True, null=True)),
                ('EAN2', models.TextField(blank=True, null=True)),
                ('supplierSKU', models.CharField(blank=True, max_length=255, null=True)),
                ('supportInfo', models.TextField(blank=True, null=True)),
                ('licenceType', models.CharField(blank=True, max_length=255, null=True)),
                ('brandName', models.CharField(blank=True, max_length=255, null=True)),
                ('nameDefault', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('packshotImage', models.URLField(blank=True, null=True)),
                ('yearsValid', models.CharField(blank=True, max_length=255, null=True)),
                ('client_fields', models.TextField(blank=True, null=True)),
                ('numberOfUsers', models.CharField(blank=True, max_length=255, null=True)),
                ('stock', models.CharField(blank=True, max_length=255, null=True)),
                ('acquisitionPrice', models.FloatField(blank=True, null=True)),
                ('client_mandatory', models.BooleanField(blank=True, null=True)),
                ('productGroup', models.CharField(blank=True, max_length=255, null=True)),
                ('downloadCode', models.CharField(blank=True, max_length=255, null=True)),
                ('downloadLink', models.URLField(blank=True, null=True)),
                ('shortDownloadLink', models.URLField(blank=True, null=True)),
                ('directDownloadLink_fr', models.URLField(blank=True, null=True)),
                ('directDownloadLink_en', models.URLField(blank=True, null=True)),
                ('directDownloadLink_de', models.URLField(blank=True, null=True)),
                ('directDownloadLink_es', models.URLField(blank=True, null=True)),
                ('directDownloadLink_nl', models.URLField(blank=True, null=True)),
                ('directDownloadLink', models.URLField(blank=True, null=True)),
                ('name_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('name_de', models.CharField(blank=True, max_length=255, null=True)),
                ('name_es', models.CharField(blank=True, max_length=255, null=True)),
                ('name_nl', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_de', models.TextField(blank=True, null=True)),
                ('description_es', models.TextField(blank=True, null=True)),
                ('description_nl', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('shortDescription_en', models.TextField(blank=True, null=True)),
                ('shortDescription_fr', models.TextField(blank=True, null=True)),
                ('shortDescription_de', models.TextField(blank=True, null=True)),
                ('shortDescription_es', models.TextField(blank=True, null=True)),
                ('shortDescription_nl', models.TextField(blank=True, null=True)),
                ('shortDescription', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dsd_product', to='catalogue.Product')),
            ],
            options={
                'verbose_name': 'DSD Product',
            },
        ),
    ]
