
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-01T14:41:12-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "8be399d5317a859091ab3051421f4a12aa626131",
 "version": "1.41.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
