env:
  browser: true
  commonjs: true
  es6: true
extends:
  - airbnb
  - "plugin:@typescript-eslint/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
plugins:
  - "@typescript-eslint"
rules: {}
