# This is a common .travis.yml for generating library release zip files for
# CircuitPython library releases using circuitpython-build-tools.
# See https://github.com/adafruit/circuitpython-build-tools for detailed setup
# instructions.

dist: xenial
language: python
python:
  - "3.6"

cache:
  pip: true
env:
  - DEPLOY_PYPI="true"

deploy:
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file_glob: true
    file: "$TRAVIS_BUILD_DIR/bundles/*"
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
  # TODO: Use 'travis encrypt your-password-here' to generate
  #       the encrypted password for your account. Paste result below.
  - provider: pypi
    user: 2bndy5
    password:
      secure: "Rn5kjXiWeG8Qlex6ZdS8sontrTaYZIFt7O/6xP5mfp9n1uxyumzteN5llI6wCDxlDPMtsvfhbWMvK+zeGJUQLyzK52t5IIWo0vULbIIZRdaJ74Djsnxh43i8siYSlNu+4VCpqfdR5o9wEU8lte53RtST9DLLk1NgokPBrRuC1uj5WGHnbVaq24QjWpDYWFw+/MtFSSbBGDPDf/s1qJnsH4LSUF95hnl1hwEyk7+0euy3wcpmDB1gqC+RRmwACiVP0qXpIroEVjRvKMjq9C0VvUQowZ/urt4isWVYrO/JT+WA2/BcLep1ep7zF46YUob1HxUqgsx04xx4y8EBbwc6yuI8xbukBIqk6DzEaFZAn5b/JFRzAOT9hbg3WYjkmtSQ2WIfb++ThnadfPhgQegrD0yBhb8UsQZeOXVWUEeSwQm4p1qQYeftfptLCkdGkamOzaijABYH8g4Rsj3oisqRMBkKE55lMcX/quggchSvASi/A/OhR/LcNX58m5yOu4rEWxdh6UEV+X7zpWDdqSMwYnCfAvrg+J7SjOYVmrfefCKRbu5I1MHO9tivZ33izUKxYeko5AexAqkoD+y1Na2PfMZi2tv2XtqPBdA6mzQwnWLNNp+xjSgntUc5VS97CpcJ1YDWiXdmhXVwy3bq1+cyN3npsAKeEySowDgtJWsS5yo="
    on:
      tags: true
      condition: $DEPLOY_PYPI = "true"

install:
  - pip install -r requirements.txt
  - pip install circuitpython-build-tools Sphinx sphinx-rtd-theme
  - pip install --force-reinstall pylint==1.9.2

script:
  - pylint --disable=invalid-name,too-many-instance-attributes,too-many-public-methods,too-many-arguments,too-many-function-args,too-many-locals,too-many-branches,too-many-nested-blocks,inconsistent-return-statements,too-many-statements,too-many-lines,invalid-name circuitpython_nrf24l01/*.py
  - ([[ ! -d "examples" ]] || pylint --disable=invalid-name examples/*.py)
  - circuitpython-build-bundles --library_location . --filename_prefix circuitpython-nrf24l01 --package_folder_prefix "circuitpython_nrf24l01"
  - cd docs && sphinx-build -E -W -b html . _build/html && cd ..
