# Hello World for AWS Lambda
service: sampleapp  # Service Name

provider:
  name: aws
  runtime: python2.7

functions:
  helloWorld:
    handler: handler.hello

package:
  exclude:
    - node-dependencies-*
    - make.cmd
    - Makefile
    - Makefile.py
    - package.json
