
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "98a1e61fcf9230e3a4dcdf8523e435ed83dfb2c0",
 "version": "2.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
