[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "crystallography"
version = "0.0.0"
description = "Library for dealing with crystallography."
license = "MIT"
authors = [
    "Dominik Steinberger <crystallography@steinberger.io>",
    "Stefan Sandfeld <stefan.sandfeld@imfd.tu-freiberg.de>",
]
readme = "README.md"
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Physics",
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^5.0"
pytest-cov = "^2.7"
black = {version = "^19.3b0",python = "^3.6"}
pre-commit = "^1.17"
tox = "^3.13"
flake8 = "^3.7"
flake8-bugbear = "^19.3"
pylint = "^2.3"
isort = "^4.3"
seed-isort-config = "^1.9"
yamllint = "^1.16"
pycodestyle = "^2.5"
pydocstyle = "^4.0"
bump2version = "^0.5"
