# Travis-CI build script for cobs

language: cpp

sudo: false
dist: bionic

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-setuptools
      - python3-sphinx

matrix:
  include:
    # gcc 7.x, Debug with -O1
    - env: CMAKE_CC="gcc" CMAKE_CXX="g++" BUILD_TYPE="Debug" COMPILER_FLAGS="-O1"

    # gcc 7.x, Release
    - env: CMAKE_CC="gcc" CMAKE_CXX="g++" BUILD_TYPE="Release" COMPILER_FLAGS=""

before_script:

  # print out some version numbers
  - $CMAKE_CXX --version
  - cmake --version

  # configure
  - mkdir build; cd build
  - cmake
      -DCMAKE_BUILD_TYPE="$BUILD_TYPE"
      -DCMAKE_C_COMPILER="$CMAKE_CC" -DCMAKE_CXX_COMPILER="$CMAKE_CXX"
      -DCMAKE_C_FLAGS="$COMPILER_FLAGS" -DCMAKE_CXX_FLAGS="$COMPILER_FLAGS"
      $CMAKE_ARGS ..

script:
  # build and run tests
  - make -j2 && ctest -V

  # install and test python module
  - cd $TRAVIS_BUILD_DIR && rm -rf build
  - pip3 install --user --verbose .
  - cd python && python3 -m unittest

after_success:
  # build docs
  - pip3 install --user sphinx-rtd-theme
  - cd $TRAVIS_BUILD_DIR/python/docs && make html
  - touch _build/html/.nojekyll

deploy:
  provider: pages
  local_dir: $TRAVIS_BUILD_DIR/python/docs/_build/html/
  repo: bingmann/cobs-python-docs
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: master
  on:
    branch: master
    condition: $BUILD_TYPE = Release
