[tool.poetry]
name = "nbwatch"
version = "0.2.2"
description = "Preview IPython notebooks in your browser."
authors = ["Jeremiah Boby <mail@jeremiahboby.me>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
docopt = "^0.6.2"
flask = "^1.1.1"
nbconvert = "^5.6.1"
jupyter_client = "^5.3.4"
ipykernel = "^5.1.3"

[tool.poetry.scripts]
nbwatch = "nbwatch:run"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
