# Generated by Django 2.1.7 on 2019-03-05 18:58

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('context', '0003_auto_20190301_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity_Relation_Type_Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('related_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context.Entity_Relation_Type')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['last_modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entity_Type_Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('related_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context.Entity_Type')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['last_modified'],
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Entity_Trait_Type',
            new_name='Trait_Type',
        ),
        migrations.AddField(
            model_name='entity_type_trait',
            name='trait_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='context.Trait_Type'),
        ),
        migrations.AddField(
            model_name='entity_relation_type_trait',
            name='trait_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='context.Trait_Type'),
        ),
    ]
