# Generated by Django 2.2 on 2019-04-24 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0006_auto_20190419_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['vocabulary', 'value']},
        ),
        migrations.CreateModel(
            name='Entity_Relation_Identifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('uuid', models.TextField(blank=True, null=True)),
                ('id_type', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('entity_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context.Entity_Relation')),
            ],
            options={
                'ordering': ['id_type', 'source', 'name', 'uuid'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entity_Identifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('uuid', models.TextField(blank=True, null=True)),
                ('id_type', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context.Entity')),
            ],
            options={
                'ordering': ['id_type', 'source', 'name', 'uuid'],
                'abstract': False,
            },
        ),
    ]
