# Generated by Django 2.2.4 on 2019-08-21 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0015_entity_relation_type_relation_through_entity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity_Identifier_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('type_list', models.ManyToManyField(to='context.Entity_Type')),
            ],
            options={
                'ordering': ['source', 'name'],
            },
        ),
        migrations.AddField(
            model_name='entity_identifier',
            name='entity_identifier_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='context.Entity_Identifier_Type'),
        ),
    ]
