# Generated by Django 2.2.4 on 2019-09-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0018_auto_20190821_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='entity_type',
            field=models.ManyToManyField(through='context.Entity_Types', to='context.Entity_Type'),
        ),
    ]
