# Generated by Django 2.2.4 on 2019-09-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0023_entity_trait_entity_type_trait'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity_identifier_type',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entity_identifier_type',
            name='name',
            field=models.SlugField(default='setme', unique=True),
            preserve_default=False,
        ),
    ]
