
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-01T11:26:16+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ac79ceff66b692bc30ad93a60621b1dcf07db51c",
 "version": "0.30.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
