
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-14T14:59:30-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "e298284ed4778307c6e8145647eddf9bb17f752e",
 "version": "0.9.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
