
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-06T16:33:38+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "f4153e7a65fdb0bd84095ea5009dce1fced3b4f2",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
