from zpcpssupport.upload_image import prepareImageResourceBeforeUpload, uploadImagesToZPSVN
from zpcpssupport.rename import renameAllFolderAndFile, renameToRemoveResolutionSuffix
from zpcpssupport.common import yes_no, choose_environment, choose_multi_environment
