
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-04T14:48:05+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "95e656908f72a0f05f214d37618a3b3c1dfa9508",
 "version": "0.4.95"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
