# Generated by Django 2.2.1 on 2019-05-02 15:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0010_auto_20190501_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity_relation',
            name='relation_from_entity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relation_from_entity_type_set', to='context.Entity_Type'),
        ),
        migrations.AddField(
            model_name='entity_relation',
            name='relation_to_entity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relation_to_entity_type_set', to='context.Entity_Type'),
        ),
        migrations.AddField(
            model_name='term_relation',
            name='details_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
