# Generated by Django 2.2.4 on 2019-08-07 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0012_auto_20190502_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity_relation',
            name='relation_through',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relation_through_entity_set', to='context.Entity'),
        ),
    ]
