environment:
  n_semitones: 25
  n_roll_steps: 33
  observation_decay: 0.75
  n_draws_per_roll_step: 3
  scoring_coefs:
    noncyclicity: 250
    usage_of_tonic: 30
    lines: 1
    conjunct_motion: 2
    contrary_motion: 1
    consonances: 1
    absence_of_outer_notes: 1
    absence_of_stalled_notes: 1
  scoring_fn_params:
    consonances:
      interval_consonances:
        0: 0
        1: -3
        2: -3
        3: 1
        4: 1
        5: 0
        6: -5
        7: 2
        8: 1
        9: 1
        10: -3
        11: -3
      distance_weights:
        0: 1
  rendering_params:
    dir: rlmusician_data
    lowest_note: C4
    step_in_seconds: 0.5
    midi:
      instrument: 0
      velocity: 100
    sinethesizer:
      timbre: default_timbre
      volume: 0.2
agent:
  population_size: 150
  elite_fraction: 0.1
  n_episodes_per_candidate: 10
  aggregation_fn: mean
  smoothing_coef: 0.25
  weights_std: 1.0
