# coding: utf-8

"""
    Pulp 3 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_deb
from pulpcore.client.pulp_deb.models.installer_package import InstallerPackage  # noqa: E501
from pulpcore.client.pulp_deb.rest import ApiException


class TestInstallerPackage(unittest.TestCase):
    """InstallerPackage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstallerPackage(self):
        """Test InstallerPackage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pulpcore.client.pulp_deb.models.installer_package.InstallerPackage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
