__version__      = '0.0.3'
__description__  = 'Fuses two XML markups together'
__url__          = 'https://github.com/innodatalabs/xmlfuse'
__author__       = 'Mike Kroutikov'
__author_email__ = 'mkroutikov@innodata.com'
__keywords__     = 'lxml xml merge fuse'
