
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-06T21:19:05-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9d9e0479c3423490ab8c2ba877f19e419c13c7ca",
 "version": "0.1.0a7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
