[tool.poetry]
name = "nbwatch"
version = "0.1.0"
description = "Preview IPython notebooks in your browser."
authors = ["Jeremiah Boby <mail@jeremiahboby.me>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
docopt = "^0.6.2"
flask = "^1.1.1"
nbconvert = "^5.6.1"

[tool.poetry.scripts]
nbwatch = "nbwatch:run"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
