# Generated by Django 2.2.4 on 2019-11-03 23:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImpressionSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default_service', models.CharField(blank=True, default='default', max_length=255)),
                ('email_host', models.CharField(blank=True, default='localhost', max_length=255)),
                ('email_port', models.PositiveIntegerField(default=25, validators=[django.core.validators.MaxValueValidator(65535)])),
                ('email_username', models.CharField(blank=True, max_length=255)),
                ('email_password', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Impression Settings',
                'verbose_name_plural': 'Impression Settings',
            },
        ),
    ]
