
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-07T13:44:51+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "abf499539f3457e9ffe49adabfae3eb247c9fb1f",
 "version": "1.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
