version: "2.4"
services:
  node_foreign:
    image: parity/parity:stable
    command:
      - "--light"
      - "--no-download"
      - "--auto-update=none"
      - "--chain=${FOREIGN_NETWORK_NAME}"
      - "--base-path=/data"
      - "--no-hardware-wallets"
      - "--jsonrpc-interface=all"
      - "--jsonrpc-apis=safe"
      - "--jsonrpc-hosts=all"
      - "--jsonrpc-cors=all"
      - "--no-ipc"
      - "--no-secretstore"
      - "--no-color"
    volumes: ["./data/${FOREIGN_NETWORK_NAME}:/data"]
    restart: unless-stopped
    mem_limit: 1G
    mem_reservation: 16M
    stop_grace_period: 3m

  node_home:
    command:
      - "--parity-args"
      - "--light"
      - "--no-hardware-wallets"
      - "--jsonrpc-apis=safe"
      - "--jsonrpc-hosts=all"
      - "--jsonrpc-cors=all"
      - "--no-ipc"
      - "--no-secretstore"
    volumes:
      [
        "./data/${HOME_NETWORK_NAME}:/home/parity/.local/share/io.parity.ethereum/chains_light",
      ]
    restart: unless-stopped
    mem_limit: 1G
    mem_reservation: 16M
    stop_grace_period: 3m

  validator:
    env_file:
      - ../.env
    restart: unless-stopped
    mem_limit: 512M
    mem_reservation: 16M
    stop_grace_period: 30s
