[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "tailpipe"
author = "Jeremy Axmacher"
author-email = "jeremy@obsoleter.com"
home-page = "https://example.com"
requires = [
    "certifi==2019.9.11",
    "chardet==3.0.4",
    "Click==7.0",
    "colorama==0.4.1",
    "idna==2.8",
    "prompt-toolkit==2.0.10",
    "Pygments==2.4.2",
    "pypager==0.3",
    "python-gitlab==1.12.1",
    "requests==2.22.0",
    "six==1.12.0",
    "urllib3==1.25.6",
    "wcwidth==0.1.7",
]
description-file="README.md"
classifiers=[
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.flit.scripts]
tailpipe = "tailpipe:main"
