[tool.poetry]
name = "escarpolette"
version = "0.1.0"
description = ""
authors = ["Alexandre Morignot <erdnaxeli@cervoi.se>"]

[tool.poetry.dependencies]
python = "^3.6"
sqlalchemy = "^1.2"
flask = "^1.0"
flask-sqlalchemy = "^2.3"
flask-cors = "^3.0"
youtube-dl = "^2019.1"
flask-restplus = "^0.12.1"
flask-migrate = "^2.5"

[tool.poetry.dev-dependencies]
pytest = "^4.1"
black = {version = "^18.3-alpha.0",allows-prereleases = true}
mypy = "^0.740.0"
radon = "^4.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
