version: 1
formatters:
  simple:
    format: '[%(asctime)s] [%(process)d] [%(levelname)s] [%(name)s:%(lineno)d] %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S %z'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    filename: 'logs/tir.log'
    formatter: simple
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8
loggers:
  tir:
    level: DEBUG
    handlers: [console, file]
    propagate: false
root:
  level: INFO
  handlers: [console, file]