
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-31T09:28:53-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "4b0f41a62b7232ba722c2fe64423b7daef51fd5a",
 "version": "v0.8.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
