
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-08T19:36:04-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "d6788c16ba369bdd847cd3797777d5ddf960f93a",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
