#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

install_requires = \
['certifi==2019.9.11',
 'chardet==3.0.4',
 'Click==7.0',
 'colorama==0.4.1',
 'idna==2.8',
 'prompt-toolkit==2.0.10',
 'Pygments==2.4.2',
 'pypager==0.3',
 'python-gitlab==1.12.1',
 'requests==2.22.0',
 'six==1.12.0',
 'urllib3==1.25.6',
 'wcwidth==0.1.7']

entry_points = \
{'console_scripts': ['tailpipe = tailpipe:main']}

setup(name='tailpipe',
      version='0.2',
      description='A simple command-line tool for reading the output of all jobs',
      author='Jeremy Axmacher',
      author_email='jeremy@obsoleter.com',
      url='https://example.com',
      py_modules=['tailpipe'],
      install_requires=install_requires,
      entry_points=entry_points,
     )
