dist: xenial
language: python
python:
  - "3.7"

matrix:
  fast_finish: true

  include:
    # run pytest
    - python: "3.7"
      env: TOXENV=py37
    # run pre-commit hooks checks
    - python: "3.7"
      env: TOXENV=lint
    # Ensure manifest is valid
    - python: "3.7"
      env: TOXENV=manifest
    # Run mypy static type-checking script
    - python: "3.7"
      env: TOXENV=typing
    # Ensure help produces valid output
    - python: "3.7"
      env: TOXENV=help
    # Check the pypi description
    - python: "3.7"
      env: TOXENV=pypi-description
    # Check the sphinx docs
    - python: "3.7"
      env: TOXENV=docs

   # Prevent breakage by new releases
    - python: "3.7-dev"
      env: TOXENV=py37

    - python: "3.8-dev"
      env: TOXENV=py38

  # Newest release of python 3.7 can have failures since that indicates
  # an area for active development
  allow_failures:
    - python: "3.7-dev"
    - python: "3.8-dev"

before_install:
  - pip install --upgrade pip
  - pip install codecov

install:
  - pip install tox

script:
  - tox

after_success:
  - codecov
