
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-14T12:13:19-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "2d1cc422808350668a3bebdfc4c79e24c207ad29",
 "version": "v0.12.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
