
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d1afd8bed83cc09476ea871ffcc106b18498dc7f",
 "version": "1.11.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
