image: python:3.7.3

pipelines:
  default:
    - step:
        script:
          - python --version
          - pip install -e .
          - pip install safety
          - safety check
  tags:
    'v*':
      - step:
          script:
            - python --version
            - pip install -e .
            - pip install safety
            - safety check
      - step:
          script:
            - python setup.py sdist
            - pip install --upgrade pip
            - pip install twine
            - twine upload dist/*
