# coding: utf-8

"""
    KF Pipelines API

    Generated python client for the KF Pipelines server API  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kfp_server_api
from kfp_server_api.api.pipeline_service_api import PipelineServiceApi  # noqa: E501
from kfp_server_api.rest import ApiException


class TestPipelineServiceApi(unittest.TestCase):
    """PipelineServiceApi unit test stubs"""

    def setUp(self):
        self.api = kfp_server_api.api.pipeline_service_api.PipelineServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_pipeline(self):
        """Test case for create_pipeline

        """
        pass

    def test_delete_pipeline(self):
        """Test case for delete_pipeline

        """
        pass

    def test_get_pipeline(self):
        """Test case for get_pipeline

        """
        pass

    def test_get_template(self):
        """Test case for get_template

        """
        pass

    def test_list_pipelines(self):
        """Test case for list_pipelines

        """
        pass


if __name__ == '__main__':
    unittest.main()
