
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-14T11:04:20+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a874e2d7365b1b0e74b93437b55dd8a98a283b8b",
 "version": "0.3.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
