'''Package Metadata'''

__title__ = 'objectmapper'
__description__ = 'A small module for mapping between object types.'
__url__ = ''
__version__ = '0.0.6'
__author__ = 'ABoiledCarny'
__author_email__ = ''
__license__ = 'MIT'
__copyright__ = 'Copyright 2019 ABoiledCarny'
