# Generated by Django 2.2 on 2019-04-25 02:59

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('context', '0007_auto_20190424_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity_trait',
            options={},
        ),
        migrations.CreateModel(
            name='Entity_Relation_Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('entity_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context.Entity_Relation')),
                ('entity_relation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context.Entity_Relation_Type')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['last_modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entity_Relation_Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('entity_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context.Entity_Relation')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='context.Term')),
                ('trait_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='context.Trait_Type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
