# Generated by Django 2.2.1 on 2019-05-02 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0011_auto_20190502_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity_relation',
            name='relation_from_entity_type',
        ),
        migrations.RemoveField(
            model_name='entity_relation',
            name='relation_to_entity_type',
        ),
        migrations.AddField(
            model_name='entity_relation_type',
            name='relation_from_entity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relation_from_entity_type_set', to='context.Entity_Type'),
        ),
        migrations.AddField(
            model_name='entity_relation_type',
            name='relation_to_entity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relation_to_entity_type_set', to='context.Entity_Type'),
        ),
    ]
