# Generated by Django 2.2.4 on 2019-09-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0019_entity_entity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='entity_type',
        ),
        migrations.AddField(
            model_name='entity',
            name='my_entity_types',
            field=models.ManyToManyField(blank=True, null=True, through='context.Entity_Types', to='context.Entity_Type'),
        ),
    ]
