# Generated by Django 2.2.4 on 2019-09-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0020_auto_20190905_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='my_entity_types',
            field=models.ManyToManyField(blank=True, through='context.Entity_Types', to='context.Entity_Type'),
        ),
        migrations.AlterField(
            model_name='entity_identifier_type',
            name='type_list',
            field=models.ManyToManyField(blank=True, to='context.Entity_Type'),
        ),
    ]
