# Generated by Django 2.2.4 on 2019-09-05 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0022_auto_20190905_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity_trait',
            name='entity_type_trait',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='context.Entity_Type_Trait'),
        ),
    ]
