KEY_PRODUCT_ID = 'product_id'
KEY_PRODUCT_RAW_ID = 'id'
KEY_TITLE = 'title'
KEY_DESCRIPTION = 'description'
KEY_REVIEW_SCREENSHOT = 'review_screenshot'
KEY_CLEARED_FOR_SALE = 'cleared_for_sale'
KEY_REVIEW_NOTES = 'review_notes'
KEY_REFERENCE_NAME = 'reference_name'
KEY_TYPE = 'type'
KEY_ENV = 'env'
KEY_VALIDITY = 'validity'
KEY_VALIDITY_TYPE = 'validityType'
KEY_APPSTORE_PRICE = 'APPSTORE_PRICE'

KEY_WHOLESALE_PRICE_TIER = 'wholesale_price_tier'
KEY_PRICE_PLAN = 'price_plan'

CONST_ORIG_PRICE = 'orig_price'
CONST_PROMOTIONS = 'promotions'
CONST_PRICE = 'price'
CONST_PRODUCT_ID_PREF = 'product_id_pref'
CONST_AUTO_RENEWABLE = 'auto-renewable'
CONST_CONSUMABLE = 'consumable'
CONST_NON_CONSUMABLE = 'non-consumable'
CONST_SUBSCRIPTION = 'subscription'
