
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-11T16:00:22+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "309dceac74450cbc29d982bc82ccf8b35923865d",
 "version": "0.6.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
