# Generated by Django 2.2.4 on 2019-09-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NomencladorHPGD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('uid', models.IntegerField(default=0)),
                ('descripcion', models.CharField(max_length=290)),
                ('arancel', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
