repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: check-added-large-files
    -   id: check-builtin-literals
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
    -   id: pretty-format-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-xml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: name-tests-test
        args: [--django]
    -   id: sort-simple-yaml
    -   id: trailing-whitespace

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.4.0
    hooks:
    -   id: reorder-python-imports
