dist: xenial   # required for Python >= 3.7
language: python

matrix:
  include:
    - python: "3.6"
    - python: "3.7"

before_install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set auto_update_conda no --set safety_checks disabled
  - conda install -q conda pip
  # Useful for debugging any issues with conda
  - conda info -a

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - pip install --upgrade pip

  # Create a conda environment using the required packages
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda install pytorch cpuonly -c pytorch
  - conda install obspy -c conda-forge
  - pip install pytest pytest-cov codecov

install:
  # Using pip instead of setup.py ensures we install a non-compressed version of the package
  # (as opposed to an egg), which is necessary to collect coverage.
  # We still get the benefit of testing an installed version over the
  # test version to iron out installation file-inclusion bugs but can
  # also collect coverage.
  - pip install .
  # Move to home dir, otherwise we'll end up with the path to the
  # package in $PWD rather than the installed v
  - |
    cd $HOME
    export YEWS_INSTALL_PATH="$(python -c 'import os; import yews; print(os.path.dirname(os.path.abspath(yews.__file__)))')"
    echo "$YEWS_INSTALL_PATH"
    cd -

script:
  - pytest -m "not password" -m "not large_download" --cov-config .coveragerc --cov yews --cov $YEWS_INSTALL_PATH tests

after_success:
  # Necessary to run coverage combine to rewrite paths from
  # /travis/env/path/site-packages/yews to actual path
  - coverage combine .coverage
  - coverage report
  - codecov
