{% set name = "yews" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: .
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  #sha256: {{ sha256 }}
  #git_url: https://github.com/lijunzh/yews.git
  #git_tag: {{ version }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - pytest-runner
  run:
    - python >=3.6
    - numpy >=1.16
    - scipy >=1.2
    - pytorch >=1.0

test:
  imports:
    - yews

about:
  home: https://github.com/lijunzh/yews
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'Yews: Your Earthquake Waveform Solutions.'

extra:
  recipe-maintainers:
    - lijunzh
