
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-12T14:15:37+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "26e4890a4b3dfa318e98fc3bc920f24ba45d41ef",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
