[build-system]
requires = [
    'amuse-framework>=12.1.3[MPI]',
    'amuse-athena>=12.1.3',
    'amuse-bhtree>=12.1.3',
    'amuse-brutus>=12.1.3',
    'amuse-bse>=12.1.3',
    'amuse-capreole>=12.1.3',
    'amuse-evtwin>=12.1.3',
    'amuse-fastkick>=12.1.3',
    'amuse-fi>=12.1.3',
    'amuse-fractalcluster>=12.1.3',
    'amuse-gadget2>=12.1.3',
    'amuse-galactics>=12.1.3',
    'amuse-galaxia>=12.1.3',
    'amuse-halogen>=12.1.3',
    'amuse-hermite>=12.1.3',
    'amuse-hop>=12.1.3',
    'amuse-huayno>=12.1.3',
    'amuse-kepler>=12.1.3',
    'amuse-kepler-orbiters>=12.1.3',
    'amuse-mameclot>=12.1.3',
    'amuse-mercury>=12.1.3',
    'amuse-mmams>=12.1.3',
    'amuse-ph4>=12.1.3',
    'amuse-seba>=12.1.3',
    'amuse-secularmultiple>=12.1.3',
#    'amuse-simplex>=12.1.3',
    'amuse-smalln>=12.1.3',
    'amuse-sphray>=12.1.3',
    'amuse-sse>=12.1.3',
    'amuse-twobody>=12.1.3',
]
