[tool.poetry]
name = "yaenv"
version = "1.2.0"
readme = "README.rst"
license = "BSD-3-Clause"
description = "Yet another dotenv parser for Python."
homepage = "https://github.com/ObserverOfTime/yaenv"
documentation = "https://yaenv.readthedocs.io"
authors = [
    "ObserverOfTime <chronobserver@disroot.org>",
]
keywords = [
    "12factor",
    "config",
    "configuration",
    "django",
    "dotenv",
    "environment",
    "variables",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
]

[[tool.poetry.packages]]
include = "yaenv"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dependencies.cached-property]
version = "1.5.1"
python = "<3.8"

[tool.poetry.dev-dependencies]
pytest = "5.1.2"
pytest-cov = "2.8.1"
sphinx = "2.2.0"
sphinx-rtd-theme = "0.4.3"
flake8 = "3.7.8"
flake8-docstrings = "1.4.0"
flake8-mypy = "17.8.0"

[tool.poetry.dev-dependencies.pytest-pspec]
git = "https://github.com/ROpdebee/pytest-pspec"
branch = "aad7ff1"

[tool.poetry.extras]
test = [
    "pytest",
    "pytest-cov",
    "pytest-pspec",
]
docs = [
    "sphinx",
    "sphinx-rtd-theme",
]
lint = [
    "flake8",
    "flake8-docstrings",
    "flake8-mypy",
]

[tool.poetry.urls]
"Bug tracker" = "https://github.com/ObserverOfTime/yaenv/issues"

[tool.pytest]
addopts = "--pspec --cov-report=term --cov=yaenv"
testpaths = "tests"

[tool.flake8]
exclude = """
    .git,
    .venv,venv,
    build,dist,
    __pycache__,
    docs/conf.py,
    tests/*,
"""
docstring_convention = "numpy"

[build-system]
requires = ["poetry==1.0.0b3"]
build-backend = "poetry.masonry.api"
