image: $DOCKER_REGISTRY/pdsl/rdiffweb-build:$CI_PIPELINE_IID

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
- prebuild
- test
- package
- publish
- deploy

prebuild-docker-image:
  image: docker:stable
  stage: prebuild
  script:
  - docker login $DOCKER_REGISTRY -u $DOCKER_USR -p $DOCKER_PWD
  - docker build -t rdiffweb-build extras/prebuild
  - docker tag rdiffweb-build $DOCKER_REGISTRY/pdsl/rdiffweb-build:$CI_PIPELINE_IID
  - docker push $DOCKER_REGISTRY/pdsl/rdiffweb-build:$CI_PIPELINE_IID

.tox:  &tox
  stage: test
  script:
  - tox -e $CI_JOB_NAME --sitepackages
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .cache/pip
  artifacts:
    paths:
    - coverage-*.xml
    - nosetests-*.xml
    expire_in: 1 day

py27-jinja26: 
  <<: *tox

py27-jinja27: 
  <<: *tox

py27-jinja28: 
  <<: *tox

py27-jinja29: 
  <<: *tox

py27-jinja210: 
  <<: *tox
  
py3-jinja26: 
  <<: *tox

py3-jinja27: 
  <<: *tox

py3-jinja28: 
  <<: *tox

py3-jinja29: 
  <<: *tox

py3-jinja210: 
  <<: *tox

py27-cherrypy35: 
  <<: *tox
  
py27-cherrypy4: 
  <<: *tox
  
py27-cherrypy5: 
  <<: *tox
  
py27-cherrypy6: 
  <<: *tox
  
py27-cherrypy7: 
  <<: *tox
  
py27-cherrypy8: 
  <<: *tox
  
py27-cherrypy9: 
  <<: *tox
  
py27-cherrypy10: 
  <<: *tox
  
py27-cherrypy11: 
  <<: *tox
  
py27-cherrypy12: 
  <<: *tox
  
py27-cherrypy13:  
  <<: *tox
  
py27-cherrypy14: 
  <<: *tox

py27-cherrypy15: 
  <<: *tox
  
py27-cherrypy16: 
  <<: *tox
  
py27-cherrypy17: 
  <<: *tox
  
py3-cherrypy35: 
  <<: *tox
  
py3-cherrypy4: 
  <<: *tox
  
py3-cherrypy5: 
  <<: *tox
  
py3-cherrypy6: 
  <<: *tox
  
py3-cherrypy7: 
  <<: *tox
  
py3-cherrypy8: 
  <<: *tox
  
py3-cherrypy9: 
  <<: *tox
  
py3-cherrypy10: 
  <<: *tox
  
py3-cherrypy11: 
  <<: *tox
  
py3-cherrypy12: 
  <<: *tox
  
py3-cherrypy13: 
  <<: *tox
  
py3-cherrypy14: 
  <<: *tox

py3-cherrypy15: 
  <<: *tox
  
py3-cherrypy16: 
  <<: *tox
  
py3-cherrypy17: 
  <<: *tox

py3-cherrypy18: 
  <<: *tox

package:py2: 
  stage: package
  script:
  - python2 setup.py sdist bdist_wheel
  artifacts:
    paths: 
    - dist/*.tar.gz
    - dist/*.whl
    
package:py3: 
  stage: package
  script:
  - python3 setup.py sdist bdist_wheel
  artifacts:
    paths:
    - dist/*.whl

publish:sonar:master:
  stage: publish
  image: ikus060/sonar-runner
  only:
  - master
  script:
  - sonar-runner -X -Dsonar.python.coverage.reportPath=coverage-*.xml -Dsonar.python.xunit.reportPath=nosetests-py3-cherrypy18.xml -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=$CI_PROJECT_NAME -Dsonar.exclusions=rdiffweb/controller/tests/**,rdiffweb/core/tests/**,rdiffweb/test.py -Dsonar.sources=.

publish:sonar:dev:
  stage: publish
  image: ikus060/sonar-runner
  script:
  - sonar-runner -X -Dsonar.python.coverage.reportPath=coverage-*.xml -Dsonar.python.xunit.reportPath=nosetests-py3-cherrypy18.xml -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=$CI_PROJECT_NAME-dev -Dsonar.exclusions=rdiffweb/controller/tests/**,rdiffweb/core/tests/**,rdiffweb/test.py -Dsonar.sources=.

publish_nexus:
  stage: publish
  script:
  - pip3 install wheel twine --upgrade
  - twine upload dist/* -u $NEXUS_USR -p $NEXUS_PWD --repository-url $NEXUS_PYPI_URL

publish_pypi:
  stage: publish
  only:
  - tags
  script:
  - pip3 install wheel twine --upgrade
  - twine upload dist/* -u $PYPI_USR -p $PYPI_PWD
  
rdiffweb_deploy_demo: 
  stage: deploy
  image: ikus060/ansible
  environment:
    name: staging
    url: https://demo.patrikdufresne.com
  variables:
    ANSIBLE_HOST_KEY_CHECKING: "False"
  before_script:
  - eval $(ssh-agent -s)
  - echo "$GITLAB_SSH_IDENTITY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  script:
  - python ./setup.py --version
  - export RDIFFWEB_VERSION=$(python ./setup.py --version)
  - echo RDIFFWEB_VERSION=$RDIFFWEB_VERSION
  - git clone "http://${GITLAB_USR}:${GITLAB_PWD}@git.patrikdufresne.com/pdsl/ansible-config.git"
  - cd ansible-config
  - ansible-playbook rdiffweb.yml -i pdsl --extra-vars "ansible_user=root rdiffweb_version=$RDIFFWEB_VERSION rdiffweb_default_repositories=true" --limit arbuc
