
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "3bfedcdc9add573e4fad490a8b71531d717f4bec",
 "version": "2206"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
