
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "0fcbc2850dada711b528a30b61ab16a72b7a160a",
 "version": "0.1.post28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
