---
language: python
dist: xenial

python:
  - '3.7'
  - '3.6'

install:
  - pip install -r requirements.txt
  - flit install

script:
  - pyflakes .
  - coverage run -m pytest
  - black --check --diff .

after_success:
  - pip install codecov
  - codecov
