language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
  - "pypy3.5"
env:
  - JOB=tests
  - JOB=docs

jobs:
  allow_failures:
    - python: "nightly"
    - python: "pypy3.5"

install: |
  case $JOB in
    tests) pip install .;;
    docs) pip install sphinx;;
  esac

script: |
  case $JOB in
    tests) python setup.py test;;
    docs) python setup.py build; make -C doc html man;;
  esac
