# coding: utf-8

# flake8: noqa

"""
    SPMO Service

    The Software Project Management Ontology (SPMO) is defined as a layer over the Software Process Ontology, addressing aspects related to scope, time & duration, and cost estimation of intended processes, as well as aspects related to tracking planned versus performed processes.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from spmo_client.api.organizations_api import OrganizationsApi
from spmo_client.api.person_stakeholders_api import PersonStakeholdersApi
from spmo_client.api.software_projects_api import SoftwareProjectsApi
from spmo_client.api.tracked_activities_api import TrackedActivitiesApi
from spmo_client.api.tracked_project_processes_api import TrackedProjectProcessesApi
from spmo_client.api.tracked_stakeholder_participation_api import TrackedStakeholderParticipationApi

# import ApiClient
from spmo_client.api_client import ApiClient
from spmo_client.configuration import Configuration
# import models into sdk package
from spmo_client.models.organization_ import Organization_
from spmo_client.models.person_stakeholder_ import PersonStakeholder_
from spmo_client.models.software_project_ import SoftwareProject_
from spmo_client.models.tracked_activity_ import TrackedActivity_
from spmo_client.models.tracked_project_process_ import TrackedProjectProcess_
from spmo_client.models.tracked_stakeholder_participation_ import TrackedStakeholderParticipation_
