# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-30 12:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    replaces = [('djangocms_page_image', '0001_initial'), ('djangocms_page_image', '0002_auto_20150124_0925'), ('djangocms_page_image', '0003_auto_20150125_2116'), ('djangocms_page_image', '0004_auto_20150213_1459'), ('djangocms_page_image', '0005_imageextension_preview_image'), ('djangocms_page_image', '0006_auto_20170913_1746'), ('djangocms_page_image', '0007_auto_20170914_2241')]

    initial = True

    dependencies = [
        ('cms', '0003_auto_20140926_2347'),
        ('filer', '0001_initial'),
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.Page')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='image')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='djangocms_page_image.ImageExtension')),
                ('teaser', models.TextField(blank=True, verbose_name='teaser')),
                ('show_preview', models.BooleanField(default=True, verbose_name='show preview?')),
                ('preview_image', filer.fields.image.FilerImageField(blank=True, help_text='leave blank to use page image', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preview_image_extensions', to=settings.FILER_IMAGE_MODEL, verbose_name='preview image')),
                ('extra_classes', models.CharField(blank=True, max_length=512, verbose_name='extra classes')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Page Image and Teaser',
            },
        ),
        migrations.CreateModel(
            name='ChildPagePreviewPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_page_image_childpagepreviewplugin', serialize=False, to='cms.CMSPlugin')),
                ('style', models.CharField(blank=True, default='', max_length=50, verbose_name='style')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='SiblingPagePreviewPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_page_image_siblingpagepreviewplugin', serialize=False, to='cms.CMSPlugin')),
                ('style', models.CharField(blank=True, default=b'', max_length=50, verbose_name='style')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
