# Generated by Django 2.1.9 on 2019-09-19 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0022_auto_20180620_1551'),
        ('djangocms_page_image', '0008_add_ondelete'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeaserExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaser', models.TextField(blank=True, verbose_name='teaser')),
                ('show_preview', models.BooleanField(default=True, verbose_name='show preview?')),
                ('extra_classes', models.CharField(blank=True, max_length=512, verbose_name='extra classes')),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.Title')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title_teasers', related_query_name='title_teaser', to=settings.FILER_IMAGE_MODEL, verbose_name='image')),
                ('preview_image', filer.fields.image.FilerImageField(blank=True, help_text='leave blank to use page image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='preview image')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='djangocms_page_image.TeaserExtension')),
            ],
            options={
                'verbose_name': 'Page Image and Teaser',
            },
        ),
    ]
