# Generated by Django 2.1.9 on 2019-09-23 13:10

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('djangocms_page_image', '0010_titleextension_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildPageTeasersPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_page_image_childpageteasersplugin', serialize=False, to='cms.CMSPlugin')),
                ('style', models.CharField(blank=True, choices=[('sdgs', 'Raster'), ('icon-slider', 'Slider')], default='', max_length=50, verbose_name='style')),
                ('parent_page', cms.models.fields.PageField(blank=True, help_text="If left blank, the current page's children will be shown.", null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Page', verbose_name='Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
