# Generated by Django 2.1.9 on 2019-09-25 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_page_image', '0011_childpageteasersplugin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageextension',
            name='teaser',
        ),
    ]
