repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-added-large-files
  - id: check-builtin-literals
  - id: check-byte-order-marker
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: flake8
  - id: forbid-new-submodules
  - id: mixed-line-ending
  - id: pretty-format-json
  - id: trailing-whitespace

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.730
  hooks:
  - id: mypy

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.4.1
  hooks:
  - id: python-no-eval
  - id: python-no-log-warn
  - id: python-use-type-annotations
  - id: rst-backticks

- repo: https://github.com/psf/black
  rev: 19.3b0
  hooks: [{id: black}]

- repo: https://github.com/asottile/blacken-docs
  rev: v1.3.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==19.3b0]

- repo: https://github.com/timothycrosley/isort
  rev: "4.3.21"
  hooks: [{id: isort}]
