
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-14T22:09:16+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a3f098d661d8a285b55abe3ef7f736b465ee0ae4",
 "version": "0.0.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
