
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-07T17:50:39-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "741f43d3970870ee1e63c0d7f4d65cef13bd06ae",
 "version": "0.0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
