
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-10T22:36:48-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "22ef7380d24d34b1845dee1514c9a8bf37082d83",
 "version": "0.5.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
