language: rust
dist: xenial

cache:
  cargo: true
  directories:
    - /usr/local/Cellar
    - /usr/local/Homebrew
    - /Users/travis/.pyenv

# https://gist.github.com/jkcclemens/000456ca646bd502cac0dbddcb8fa307
before_cache:
  - rm -rfv target/debug/incremental
  - rm -rfv target/debug/.fingerprint/blake2b*
  - rm -rfv target/debug/build/blake2b*
  - rm -rfv target/debug/deps/{libblake2b,blake2b}*
  - rm -rfv target/debug/{libblake2b,blake2b}*
  - cargo clean -p blake2b-py

matrix:
  fast_finish: true
  include:
    - os: linux
      rust: nightly
    - os: osx
      rust: nightly

install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update
      # For python
      brew install openssl xz || true

      brew upgrade pyenv
      pyenv install --skip-existing 3.7.4
      pyenv install --skip-existing 3.6.9

      # Doing things the normal way doesn't seem to work
      export PATH="$HOME/.pyenv/versions/3.6.9/bin:$PATH"
      export PATH="$HOME/.pyenv/versions/3.7.4/bin:$PATH"

      python3 -mpip install -r requirements-dev.txt
    fi

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      maturin build --no-sdist -i python3.7
      maturin build --no-sdist -i python3.6
    fi
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm -v $(pwd):/io --entrypoint /bin/bash konstin2/maturin:master -c \
        'rustup default nightly
        cd /io
        maturin build -i python3.7
        maturin build --no-sdist -i python3.6'
    fi

branches:
  only:
    # Pushes to the master branch
    - master
    # Match release tags with a regex
    - /^v\d+\.\d+\.\d+.*$/

notifications:
  email: false
