
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-14T10:59:39+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d56a87fd686c7bc0ff748f6ccd689a9dc6605c4e",
 "version": "0.3.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
