environment:

  # The (encrypted) password for the 'rigbots' PyPI account, used for
  # deployment.
  PYPIPASSWORD:
    secure: jgGoNl5rbK62u86B8pKUmw==

  matrix:

    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python
    # The list here is complete (excluding Python 2.6, which
    # isn't covered by this document) at the time of writing.

    - PYTHON: "C:\\Python27"
      SDIST: "yes"
    - PYTHON: "C:\\Python35"
      SDIST: "no"
    - PYTHON: "C:\\Python27-x64"
      SDIST: "no"
    - PYTHON: "C:\\Python35-x64"
      SDIST: "no"

install:
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - "python -m pip install --disable-pip-version-check --user --upgrade pip"

  # We need wheel installed to build wheels
  - "python -m pip install wheel"
  - "python -m pip install twine"

# Disable AppVeyor's attempts to automatically build the code
build: off

after_test:
  # This step builds your wheels.
  - "python setup.py bdist_wheel"
  # This step builds src dist, but only once per commit (see env above).
  - if "%SDIST%"=="yes" ( python setup.py sdist ) else ( echo "Skipping sdist" )

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*

on_success:
  # Specify account details for PyPI
  - echo [distutils]                                  > %USERPROFILE%\\.pypirc
  - echo index-servers =                             >> %USERPROFILE%\\.pypirc
  - echo     pypi                                    >> %USERPROFILE%\\.pypirc
  - echo [pypi]                                      >> %USERPROFILE%\\.pypirc
  - echo username=jeff.daily                         >> %USERPROFILE%\\.pypirc
  - echo password=%PYPIPASSWORD%                     >> %USERPROFILE%\\.pypirc

  # Workaround required to ensure setup.py finds the .pypirc under Windows
  - set HOME=%USERPROFILE%

  # Deploy a wheel (only actually do this for tags). NB That breaking this line
  # with Unix line-endings causes the windows command interpreter to barf so
  # this is given as one-line to make this script less fragile when edited on
  # other OSes.
  - if "%APPVEYOR_REPO_TAG%"=="true" ( twine upload --skip-existing dist/* ) else ( echo "Not deploying because not a tagged commit." )

