
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-02T20:01:56+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "72481274a901891a58f9487fa8ccc4cd2920ddf9",
 "version": "0.11.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
