[tool.poetry]
name = "opset"
version = "1.1.0"
description = "A library for simplifying the configuration of Python applications at all stages of deployment."
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/ElementAI/opset"
repository = "https://github.com/ElementAI/opset"
documentation = "https://github.com/ElementAI/opset"
keywords = ["config", "management", "configuration", "logging", "setup"]
authors = ["Element AI Inc. <hello@elementai.com>", "Alexandre Jutras <alexandre.jutras@elementai.com>", "Emilio Assuncao <emilio.assuncao@elementai.com>", "Guy Dumais <guy@elementai.com>", "Marc-André Dufresne <marc-andre.dufresne@elementai.com>"]
packages = [
    {include = "opset"}
]

[tool.poetry.dependencies]
python = "^3.6"
munch = "^2.3"
pytz = "^2018.9"
pyyaml = ">=3.13,<6"
python-logstash = "^0.4.6"
structlog = "^19.1"
colorama = "^0.4.1"  # for structlog colors

[tool.poetry.dev-dependencies]
flake8 = "^3.6"
pytest = "^4.1"
flake8-import-order = "^0.18.0"
pytest-cov = "^2.6"
coveralls = "^1.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
