[tool.poetry]
name = "makenew-pypackage"
version = "2.0.1"
description = "Package skeleton for a python module."
authors = ["Evan Sosenko <razorx@evansosenko.com>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/makenew/pypackage"
repository = "https://github.com/makenew/pypackage"

[tool.poetry.dependencies]
python = "3.7.5"

[tool.poetry.dev-dependencies]
bumpversion = "^0.5.3"
docutils = "^0.15.2"
pygments = "^2.4"
pylint = "^2.4"
pytest = "^5.2"
pytest-cov = "^2.8"
pytest-incremental = "^0.5.0"
pytest-runner = "^5.2"
pytest-watch = "^4.2"
twine = "^2.0"
wheel = "^0.33.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
