
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-10T15:29:53+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "118e6edaeaa7cece6535dda5a7868d4cdc9bf72a",
 "version": "0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
