
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-14T22:02:12-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "4cc879b84a6f62777c7c17569a8c54f79b3bea60",
 "version": "0.6.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
