#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['fuzzytable', 'fuzzytable.datamodel', 'fuzzytable.patterns']

package_data = \
{'': ['*'], 'fuzzytable': ['main/*', 'main\\sheet/*']}

install_requires = \
['openpyxl']

extras_require = \
{'docs': ['sphinx', 'm2r', 'sphinx-rtd-theme'],
 'test': ['pytest', 'pytest-cov', 'tox', 'names']}

setup(name='fuzzytable',
      version='0.8a0',
      description='Read tables from messy spreadsheets.',
      author='Jonathan Chukinas',
      author_email='chukinas@gmail.com',
      url='https://github.com/jonathanchukinas/excelerator',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.6.3',
     )
