[tool.poetry]
name = "aiohttp-boilerplate"
version = "0.1.7"
description = ""
authors = ["Vladyslav Tarasenko <vladka@webdevelop.pro>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
aiodns = "=2.0.0"
aiohttp = "=3.6.2"
async-timeout = "=3.0.1"
asyncpg = "=0.18.3"
attrs = "=19.3.0"
cchardet = "=2.1.4"
cffi = "=1.12.3"
chardet = "=3.0.4"
Cython = "=0.29.12"
idna = "=2.8"
marshmallow = "=2.19.5"
multidict = "=4.5.2"
pycares = "=3.0.0"
pycparser = "=2.19"
PyJWT = "=1.7.1"
ujson = "=1.35"
uvloop = "=0.12.2"
yarl = "=1.3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
