#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['hibpcli']

package_data = \
{'': ['*']}

install_requires = \
['click ==7.0', 'pykeepass == 3.1.1', 'httpx == 0.7.5']

extras_require = \
{'dev': ['pdbpp'], 'test': ['pytest >=5.2.2', 'pytest-cov']}

entry_points = \
{'console_scripts': ['hibpcli = hibpcli.cli:main']}

setup(name='hibpcli',
      version='0.3.0',
      description='A command line interface for the "haveibeenpwned.com" API - speaks keepass.',
      author='Jürgen Gmach',
      author_email='juergen.gmach@goglemail.com',
      url='https://github.com/jugmac00/hibpcli',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>=3.6',
     )
