# Generated by Django 2.2.1 on 2019-05-01 16:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0008_auto_20190425_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity_relation_trait',
            name='value_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity_trait',
            name='value_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
