# Generated by Django 2.2.4 on 2019-08-08 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0014_auto_20190807_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity_relation_type',
            name='relation_through_entity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relation_through_entity_type_set', to='context.Entity_Type'),
        ),
    ]
