# Generated by Django 2.2.4 on 2019-09-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0021_auto_20190905_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity_relation_trait',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity_trait',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
