[tool.poetry]
name = "desdeo-tools"
version = "0.1.0"
description = "Generic tools and design language used in the DESDEO framework"
authors = ["Bhupinder Saini"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.17"
pandas = "^0.25.3"
jupyter = "^1.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
pylint = "^2.4"
black = {version = "^18.3-alpha.0", allows-prereleases = true}
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
