# This is a common .travis.yml for generating library release zip files for
# CircuitPython library releases using circuitpython-build-tools.
# See https://github.com/adafruit/circuitpython-build-tools for detailed setup
# instructions.

dist: xenial
language: python
python:
  - "3.6"

cache:
  pip: true

# TODO: if deployment to PyPi is desired, change 'DEPLOY_PYPI' to "true",
#       or remove the env block entirely and remove the condition in the
#       deploy block.
env:
  - DEPLOY_PYPI="true"

deploy:
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file_glob: true
    file: "$TRAVIS_BUILD_DIR/bundles/*"
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
  # TODO: Use 'travis encrypt --com -r adafruit/<repo slug>' to generate
  #       the encrypted password for adafruit-travis. Paste result below.
  - provider: pypi
    user: adafruit-travis
    password:
      secure: mK1brDPZMNqHXM83DNW+FxcwiWIeJXg4xMVkSCPLxCgB6sSd9S7uVjsQvxSy6TRKnM6X0n4BZDwYlgGMW80EODaM0LNgg7lB/VGa/ZAAPezXzAnZ12sVwpFkhr8DxlOZzGtQ7vODPiassuGPUzjyUX+pqoX8CIqeW9gHXduJY7sPdakVOQ565oV0Bm6VrcuNpHVtIVhlza+QZ8t/K4crVf0pl/p40cidyA01BeL2OXhjVQEbObu61YRv3DTmBKZSR3XtXFbeDwhl75k83Y2jyh9qdZyClA6/RtWrc5LicXEqCjrZMMKCdyXxEQcMIsQuDK0I+uPUfu6qgnqmeH5B2zYA0QXXjLf4QEJMmscRoespLTHJ4xatg+15/DpJhy5SguPdm/YeU+Ij3IgAP/Mj6IEKSDI9I1evVn9fdfFIMvz9EPScZanCuMpQZxMYDSAShofWwYqbhkKVaEAX7XmEyBxfVtOlalMRo+hW5MnB9wnNI8Ylooznrin6JkiTx95TZ6+sxdwXlvZqPwZ/rNhbNn9xWx/Qj/7HnjIvgNPYUXMOMnWeOHQgNxXGvVbgl+XT/F394cTgTi1f74dp32+D0GE6JO6GUQOKDFRzJF/N8NQzvSGn4CUnWE0c7QALcsw5TlKZ+HWrNyiQ7nlBrq59hj4LxBthFHtsE62xdqII9d4=
    on:
      tags: true
      condition: $DEPLOY_PYPI = "true"

install:
  - pip install -r requirements.txt
  - pip install circuitpython-build-tools Sphinx sphinx-rtd-theme
  - pip install --force-reinstall pylint==1.9.2

script:
  - pylint adafruit_display_shapes/*.py
  - ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name,bad-whitespace examples/*.py)
  - circuitpython-build-bundles --filename_prefix adafruit-circuitpython-display_shapes --library_location .
  - cd docs && sphinx-build -E -W -b html . _build/html && cd ..
