[tool.poetry]
name = "beanbot"
version = "0.1.0"
description = ""
authors = ["Kevin Zúñiga <kevin.zun@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
python-telegram-bot = "^12.2.0"
django = "^2.2.7"
pytz = "^2019.3"

[tool.poetry.dev-dependencies]
ipython = "^7.9.0"
flake8 = "^3.7.9"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
