
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-07T18:11:50-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "439e04cb5d0332d5f8b14059b7d9bd319127804b",
 "version": "0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
