
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-04T08:30:06+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4587fea098712029469cc1665391c79ab7891e4a",
 "version": "1.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
