
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.8.0'
version_full = 'ef52b98b9f5e753a07cf5ce7495ff734187be3ad'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

