#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['project_runpy']

package_data = \
{'': ['*']}

setup(name='project_runpy',
      version='1.0.1',
      description='Helper utilities for Python projects',
      author='Chris Chang',
      author_email='c@crccheck.com',
      url='https://github.com/crccheck/project_runpy',
      packages=packages,
      package_data=package_data,
      python_requires='>=3',
     )
