
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-12T16:42:14-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b0369776680bfda5681f72d7c3fdc2c88c7bcfdf",
 "version": "2.1.5.dev"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
