language: python
sudo: false
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
python:
  - 2.7
env:
  - PLONE_VERSION=4.3
  - PLONE_VERSION=5.0
  - PLONE_VERSION=5.1
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - mkdir $HOME/.buildout
  - echo "[buildout]" > $HOME/.buildout/default.cfg
  - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
  - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
install:
  - sed -ie "s#test-4.3#test-$PLONE_VERSION#" buildout.d/base.cfg
  - sed -ie "s#travis-4.3#travis-$PLONE_VERSION#" travis.cfg
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg annotate
  - bin/buildout -c travis.cfg
script:
  - bin/test
after_success:
  - bin/coverage run bin/test
  - pip install --upgrade pip
  - pip install -q coveralls==0.5
  - coveralls
notifications:
  email:
    - travis-reports@ecreall.com
    - devs@imio.be
