
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-08T17:43:46-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "22e0f9bf90c71e20a6bb30544483af46e5b2bd52",
 "version": "0.4.0rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
