sudo: false
cache: pip
language: python
python:
- 3.6
stages:
  - lint
  - docs
  - test
jobs:
  include:
    # lint stage
    - stage: lint
      env: TOXENV=manifest
    - env: TOXENV=flake8
    - env: TOXENV=flake8-kegg
    - env: TOXENV=xenon
    - env: TOXENV=vulture
    - env: TOXENV=pyroma
    # docs stage
    - stage: docs
      env: TOXENV=doc8
    - env: TOXENV=readme
    - env: TOXENV=docs
    # test stage
    - stage: test
      env: TOXENV=py
    - env: TOXENV=py PATHME_TESTS=tests/test_kegg/
matrix:
  allow_failures:
      - env: TOXENV=flake8
      - env: TOXENV=xenon
      - env: TOXENV=vulture
install:
- pip install --upgrade pip
- pip install tox
- pip install codecov
- pip install coverage
script:
- tox
after_success:
- tox -e coverage-report
- codecov
notifications:
  slack: pybel:n2KbWKBum3musnBg3L76gGwq
